export const completion: Fig.Spec = {
  name: "#",
  description: "",

  // Only uncomment if # takes an argument
  args: {
    name: "OpenAI Codex",
    description: "Type `?` to trigger suggestions",
    variadic: true,
    generators: {
      trigger: "?",
      filterTerm: "?",
      custom: async (tokens) => {
        console.log("custom gen is running");
        console.log({ tokens });
        if (!tokens[tokens.length - 1].includes("?")) return [];
        try {
          var query: string = tokens.slice(1).join(" ").trim().slice(0, -1);

          if (!query) {
            console.log("Query was empty, returning early");
            return [];
          }

          var out = await window.fetch("https://waitlist.withfig.com//codex", {
            body: JSON.stringify({
              query,
            }),
            method: "POST",
          });

          var choice = await out.text();
          console.log(choice);

          var suggestion: Fig.Suggestion = {
            name: choice,
            insertValue: `\n` + choice,
            description: "Generated by OpenAI's Codex",
          };
          return [suggestion];
        } catch (err) {
          console.log({ err });
          return [{ name: "error" }];
        }
      },
    },
  },
};
