const completionSpec: Fig.Spec = {
  name: "vultr-cli",
  description: "Official command line interface for the Vultr API",
  icon: "https://www.vultr.com/favicon/favicon-32x32.png",
  subcommands: [
    { name: "account", description: "Retrieve information about your account" },
    {
      name: "apps",
      description: "Display all available applications",
      subcommands: [{ name: "list", description: "List applications" }],
    },
    {
      name: "backups",
      description: "Display backups",
      subcommands: [
        { name: "get", description: "Get backup" },
        { name: "list", description: "List backups" },
      ],
    },
    {
      name: "bare-metal",
      description: "Bare-metal is used to access bare metal server commands",
    },
    { name: "block-storage", description: "Block storage commands" },
    {
      name: "completion",
      description: "Generate the autocompletion script for the specified shell",
    },
    { name: "dns", description: "Dns is used to access dns commands" },
    {
      name: "firewall",
      description: "Firewall is used to access firewall commands",
    },
    { name: "help", description: "Help about any command" },
    {
      name: "instance",
      description: "Commands to interact with instances on vultr",
      subcommands: [
        { name: "app", description: "Update application for an instance" },
        {
          name: "backup",
          description: "List and create backup schedules for an instance",
        },
        { name: "bandwidth", description: "Bandwidth for instance" },
        { name: "create", description: "Create an instance" },
        { name: "delete", description: "Delete/destroy an instance" },
        { name: "get", description: "Get info about a specific instance" },
        { name: "image", description: "Update image for an instance" },
        { name: "ipv4", description: "List/create/delete ipv4 on instance" },
        { name: "ipv6", description: "Commands for ipv6 on instance" },
        { name: "iso", description: "Attach/detach ISOs to a given instance" },
        { name: "label", description: "Label an instance" },
        { name: "list", description: "List all available instances" },
        { name: "os", description: "Update operating system for an instance" },
        { name: "plan", description: "Update/list plans for an instance" },
        { name: "reinstall", description: "Reinstall an instance" },
        { name: "restart", description: "Restart an instance" },
        {
          name: "restore",
          description: "Restore instance from backup/snapshot",
        },
        {
          name: "reverse-dns",
          description: "Commands to handle reverse-dns on an instance",
        },
        { name: "start", description: "Starts an instance" },
        { name: "stop", description: "Stops an instance" },
        { name: "tag", description: "Add/modify tag on instance" },
        {
          name: "update-firewall-group",
          description: "Assign a firewall group to instance",
        },
        {
          name: "user-data",
          description: "Commands to handle userdata on an instance",
        },
      ],
    },
    { name: "iso", description: "Iso is used to access iso commands" },
    {
      name: "kubernetes",
      description: "Kubernetes is used to access kubernetes commands",
    },
    { name: "load-balancer  ", description: "Load balancer commands" },
    { name: "network", description: "Network interacts with network actions" },
    { name: "object-storage ", description: "Object storage commands" },
    { name: "os", description: "Os is used to access os commands" },
    { name: "plans", description: "Get information about Vultr plans" },
    { name: "regions", description: "Get regions" },
    {
      name: "reserved-ip",
      description: "Reserved-ip lets you interact with reserved-ip",
    },
    { name: "script", description: "Startup script commands" },
    { name: "snapshot", description: "Snapshot commands" },
    { name: "ssh-key", description: "Ssh-key commands" },
    { name: "user", description: "User commands" },
    { name: "version", description: "Display current version of Vultr-cli" },
  ],
};
export default completionSpec;
