name: Completion Spec Issue
title: "[CLI_NAME]"
description: All issues relating to specific CLI tools (e.g. `git`, `kubectl`, `chmod`)
labels: [NEED_TO_LABEL]
body:
  - type: checkboxes
    attributes:
      label: Sanity checks
      options:
        - label: "My issue relates to a specific CLI completion spec (e.g. `git checkout` is missing options in `git` completion spec). If your issue is more general, please create your issue here: [withfig/fig](https://github.com/withfig/fig/issues/new?assignees=&labels=NEED_TO_LABEL&template=main_issue_template.yml)"
          required: true
        - label: "I have searched [github.com/withfig/autocomplete/issues](https://github.com/withfig/autocomplete/issues?q=) and there are no duplicates of my issue"
          required: true
        - label: "I would like to work on this."
  - type: input
    attributes:
      label: What CLI tool does this relate to?
      description: "If it relates to all of them, you probably want to create your issue here: [withfig/fig](https://github.com/withfig/fig/issues/new?assignees=&labels=NEED_TO_LABEL&template=main_issue_template.yml)"
      placeholder: "git"
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Which statement makes the most sense?
      options:
        - "There is a bug with this completion spec"
        - "There are errors with this completion spec"
        - "This completion spec does not exist"
        - "This completion spec isn't complete"
        - "Something else"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Issue Details
      description: Tell us more about the issue
      placeholder: What subcommands / options / arguments are relevant? If a generator needs to be written, please specifiy the desired output.
    validations:
      required: true
