const completionSpec: Fig.Spec = {
  name: "batchai",
  description: "Manage Batch AI resources",
  subcommands: [
    {
      name: "cluster",
      description: "Commands to manage clusters",
      subcommands: [
        {
          name: "auto-scale",
          description: "Set auto-scale parameters for a cluster",
        },
        { name: "create", description: "Create a cluster" },
        { name: "delete", description: "Delete a cluster" },
        {
          name: "file",
          description:
            "Commands to work with files generated by node setup task",
          subcommands: [
            {
              name: "list",
              description:
                "List files generated by the cluster's node setup task",
            },
          ],
        },
        { name: "list", description: "List clusters" },
        {
          name: "node",
          description: "Commands to work with cluster nodes",
          subcommands: [
            {
              name: "exec",
              description:
                "Executes a command line on a cluster's node with optional ports forwarding",
            },
            {
              name: "list",
              description: "List remote login information for cluster's nodes",
            },
          ],
        },
        { name: "resize", description: "Resize a cluster" },
        { name: "show", description: "Show information about a cluster" },
      ],
    },
    {
      name: "experiment",
      description: "Commands to manage experiments",
      subcommands: [
        { name: "create", description: "Create an experiment" },
        { name: "delete", description: "Delete an experiment" },
        { name: "list", description: "List experiments" },
        { name: "show", description: "Show information about an experiment" },
      ],
    },
    {
      name: "file-server",
      description: "Commands to manage file servers",
      subcommands: [
        { name: "create", description: "Create a file server" },
        { name: "list", description: "List file servers" },
      ],
    },
    {
      name: "job",
      description: "Commands to manage jobs",
      subcommands: [
        { name: "create", description: "Create a job" },
        { name: "delete", description: "Delete a job" },
        {
          name: "file",
          description:
            "Commands to list and stream files in job's output directories",
          subcommands: [
            {
              name: "list",
              description:
                "List job's output files in a directory with given id",
            },
            {
              name: "stream",
              description:
                "Stream the content of a file (similar to 'tail -f')",
            },
          ],
        },
        { name: "list", description: "List jobs" },
        {
          name: "node",
          description: "Commands to work with nodes which executed a job",
          subcommands: [
            {
              name: "exec",
              description:
                "Executes a command line on a cluster's node used to execute the job with optional ports forwarding",
            },
            {
              name: "list",
              description:
                "List remote login information for nodes which executed the job",
            },
          ],
        },
        { name: "show", description: "Show information about a job" },
        { name: "terminate", description: "Terminate a job" },
        {
          name: "wait",
          description:
            "Waits for specified job completion and setups the exit code to the job's exit code",
        },
      ],
    },
    {
      name: "list-usages",
      description:
        "Gets the current usage information as well as limits for Batch AI resources for given location",
    },
    {
      name: "workspace",
      description: "Commands to manage workspaces",
      subcommands: [
        { name: "create", description: "Create a workspace" },
        { name: "delete", description: "Delete a workspace" },
        { name: "list", description: "List workspaces" },
        { name: "show", description: "Show information about a workspace" },
      ],
    },
  ],
};

export default completionSpec;
