// Autogenerated by @fig/complete-commander

const completionSpec: Fig.Spec = {
  name: "bw",
  subcommands: [
    {
      name: "login",
      description: "Log into a user account",
      options: [
        {
          name: "--method",
          description: "Two-step login method",
          args: { name: "method" },
        },
        {
          name: "--code",
          description: "Two-step login code",
          args: { name: "code" },
        },
        { name: "--sso", description: "Log in with Single-Sign On" },
        { name: "--apikey", description: "Log in with an Api Key" },
        {
          name: "--passwordenv",
          description: "Environment variable storing your password",
          args: { name: "passwordenv" },
        },
        {
          name: "--passwordfile",
          description:
            "Path to a file containing your password as its first line",
          args: { name: "passwordfile" },
        },
        { name: "--check", description: "Check login status" },
        {
          name: ["-h", "--help"],
          description: "Display help for command",
          priority: 49,
        },
      ],
      args: [
        { name: "email", isOptional: true },
        { name: "password", isOptional: true },
      ],
    },
    {
      name: "logout",
      description: "Log out of the current user account",
      options: [
        {
          name: ["-h", "--help"],
          description: "Display help for command",
          priority: 49,
        },
      ],
    },
    {
      name: "lock",
      description: "Lock the vault and destroy active session keys",
      options: [
        {
          name: ["-h", "--help"],
          description: "Display help for command",
          priority: 49,
        },
      ],
    },
    {
      name: "unlock",
      description: "Unlock the vault and return a new session key",
      options: [
        { name: "--check", description: "Check lock status" },
        {
          name: "--passwordenv",
          description: "Environment variable storing your password",
          args: { name: "passwordenv" },
        },
        {
          name: "--passwordfile",
          description:
            "Path to a file containing your password as its first line",
          args: { name: "passwordfile" },
        },
        {
          name: ["-h", "--help"],
          description: "Display help for command",
          priority: 49,
        },
      ],
      args: { name: "password", isOptional: true },
    },
    {
      name: "sync",
      description: "Pull the latest vault data from server",
      options: [
        { name: ["-f", "--force"], description: "Force a full sync" },
        { name: "--last", description: "Get the last sync date" },
        {
          name: ["-h", "--help"],
          description: "Display help for command",
          priority: 49,
        },
      ],
    },
    {
      name: "generate",
      description: "Generate a password/passphrase",
      options: [
        {
          name: ["-u", "--uppercase"],
          description: "Include uppercase characters",
        },
        {
          name: ["-l", "--lowercase"],
          description: "Include lowercase characters",
        },
        {
          name: ["-n", "--number"],
          description: "Include numeric characters",
        },
        {
          name: ["-s", "--special"],
          description: "Include special characters",
        },
        { name: ["-p", "--passphrase"], description: "Generate a passphrase" },
        {
          name: "--length",
          description: "Length of the password",
          args: { name: "length" },
        },
        {
          name: "--words",
          description: "Number of words",
          args: { name: "words" },
        },
        {
          name: "--separator",
          description: "Word separator",
          args: { name: "separator" },
        },
        { name: ["-c", "--capitalize"], description: "Title case passphrase" },
        {
          name: "--includeNumber",
          description: "Passphrase includes number",
        },
        {
          name: ["-h", "--help"],
          description: "Display help for command",
          priority: 49,
        },
      ],
    },
    {
      name: "encode",
      description: "Base 64 encode stdin",
      options: [
        {
          name: ["-h", "--help"],
          description: "Display help for command",
          priority: 49,
        },
      ],
    },
    {
      name: "config",
      description: "Configure CLI settings",
      options: [
        {
          name: "--web-vault",
          description:
            "Provides a custom web vault URL that differs from the base URL",
          args: { name: "url" },
        },
        {
          name: "--api",
          description:
            "Provides a custom API URL that differs from the base URL",
          args: { name: "url" },
        },
        {
          name: "--identity",
          description:
            "Provides a custom identity URL that differs from the base URL",
          args: { name: "url" },
        },
        {
          name: "--icons",
          description:
            "Provides a custom icons service URL that differs from the base URL",
          args: { name: "url" },
        },
        {
          name: "--notifications",
          description:
            "Provides a custom notifications URL that differs from the base URL",
          args: { name: "url" },
        },
        {
          name: "--events",
          description:
            "Provides a custom events URL that differs from the base URL",
          args: { name: "url" },
        },
        {
          name: "--key-connector",
          description: "Provides the URL for your Key Connector server",
          args: { name: "url" },
        },
        {
          name: ["-h", "--help"],
          description: "Display help for command",
          priority: 49,
        },
      ],
      args: [{ name: "setting" }, { name: "value", isOptional: true }],
    },
    {
      name: "update",
      description: "Check for updates",
      options: [
        {
          name: ["-h", "--help"],
          description: "Display help for command",
          priority: 49,
        },
      ],
    },
    {
      name: "completion",
      description: "Generate shell completions",
      options: [
        {
          name: "--shell",
          description: "Shell to generate completions for",
          args: { name: "shell" },
        },
        {
          name: ["-h", "--help"],
          description: "Display help for command",
          priority: 49,
        },
      ],
    },
    {
      name: "status",
      description: "Show server, last sync, user information, and vault status",
      options: [
        {
          name: ["-h", "--help"],
          description: "Display help for command",
          priority: 49,
        },
      ],
    },
    {
      name: "serve",
      description: "Start a RESTful API webserver",
      options: [
        {
          name: "--hostname",
          description: "The hostname to bind your API webserver to",
          args: { name: "hostname" },
        },
        {
          name: "--port",
          description: "The port to run your API webserver on",
          args: { name: "port" },
        },
        {
          name: ["-h", "--help"],
          description: "Display help for command",
          priority: 49,
        },
      ],
    },
    {
      name: "list",
      description: "List an array of objects from the vault",
      options: [
        {
          name: "--search",
          description: "Perform a search on the listed objects",
          args: { name: "search" },
        },
        {
          name: "--url",
          description: "Filter items of type login with a url-match search",
          args: { name: "url" },
        },
        {
          name: "--folderid",
          description: "Filter items by folder id",
          args: { name: "folderid" },
        },
        {
          name: "--collectionid",
          description: "Filter items by collection id",
          args: { name: "collectionid" },
        },
        {
          name: "--organizationid",
          description: "Filter items or collections by organization id",
          args: { name: "organizationid" },
        },
        {
          name: "--trash",
          description: "Filter items that are deleted and in the trash",
        },
        {
          name: ["-h", "--help"],
          description: "Display help for command",
          priority: 49,
        },
      ],
      args: { name: "object" },
    },
    {
      name: "get",
      description: "Get an object from the vault",
      options: [
        {
          name: "--itemid",
          description: "Attachment's item id",
          args: { name: "itemid" },
        },
        {
          name: "--output",
          description: "Output directory or filename for attachment",
          args: { name: "output" },
        },
        {
          name: "--organizationid",
          description: "Organization id for an organization object",
          args: { name: "organizationid" },
        },
        {
          name: ["-h", "--help"],
          description: "Display help for command",
          priority: 49,
        },
      ],
      args: [{ name: "object" }, { name: "id" }],
    },
    {
      name: "create",
      description: "Create an object in the vault",
      options: [
        {
          name: "--file",
          description: "Path to file for attachment",
          args: { name: "file" },
        },
        {
          name: "--itemid",
          description: "Attachment's item id",
          args: { name: "itemid" },
        },
        {
          name: "--organizationid",
          description: "Organization id for an organization object",
          args: { name: "organizationid" },
        },
        {
          name: ["-h", "--help"],
          description: "Display help for command",
          priority: 49,
        },
      ],
      args: [{ name: "object" }, { name: "encodedJson", isOptional: true }],
    },
    {
      name: "edit",
      description: "Edit an object from the vault",
      options: [
        {
          name: "--organizationid",
          description: "Organization id for an organization object",
          args: { name: "organizationid" },
        },
        {
          name: ["-h", "--help"],
          description: "Display help for command",
          priority: 49,
        },
      ],
      args: [
        { name: "object" },
        { name: "id" },
        { name: "encodedJson", isOptional: true },
      ],
    },
    {
      name: "delete",
      description: "Delete an object from the vault",
      options: [
        {
          name: "--itemid",
          description: "Attachment's item id",
          args: { name: "itemid" },
        },
        {
          name: "--organizationid",
          description: "Organization id for an organization object",
          args: { name: "organizationid" },
        },
        {
          name: ["-p", "--permanent"],
          description:
            "Permanently deletes the item instead of soft-deleting it (item only)",
        },
        {
          name: ["-h", "--help"],
          description: "Display help for command",
          priority: 49,
        },
      ],
      args: [{ name: "object" }, { name: "id" }],
    },
    {
      name: "restore",
      description: "Restores an object from the trash",
      options: [
        {
          name: ["-h", "--help"],
          description: "Display help for command",
          priority: 49,
        },
      ],
      args: [{ name: "object" }, { name: "id" }],
    },
    {
      name: "move",
      description: "Move an item to an organization",
      options: [
        {
          name: ["-h", "--help"],
          description: "Display help for command",
          priority: 49,
        },
      ],
      args: [
        { name: "id" },
        { name: "organizationId" },
        { name: "encodedJson", isOptional: true },
      ],
    },
    {
      name: "confirm",
      description: "Confirm an object to the organization",
      options: [
        {
          name: "--organizationid",
          description: "Organization id for an organization object",
          args: { name: "organizationid" },
        },
        {
          name: ["-h", "--help"],
          description: "Display help for command",
          priority: 49,
        },
      ],
      args: [{ name: "object" }, { name: "id" }],
    },
    {
      name: "import",
      description: "Import vault data from a file",
      options: [
        { name: "--formats", description: "List formats" },
        {
          name: "--organizationid",
          description: "ID of the organization to import to",
          args: { name: "organizationid" },
        },
        {
          name: ["-h", "--help"],
          description: "Display help for command",
          priority: 49,
        },
      ],
      args: [
        { name: "format", isOptional: true },
        { name: "input", isOptional: true },
      ],
    },
    {
      name: "export",
      description: "Export vault data to a CSV or JSON file",
      options: [
        {
          name: "--output",
          description: "Output directory or filename",
          args: { name: "output" },
        },
        {
          name: "--format",
          description: "Export file format",
          args: { name: "format" },
        },
        {
          name: "--password",
          description:
            "Use password to encrypt instead of your Bitwarden account encryption key. Only applies to the encrypted_json format",
          args: { name: "password", isOptional: true },
        },
        {
          name: "--organizationid",
          description: "Organization id for an organization",
          args: { name: "organizationid" },
        },
        {
          name: ["-h", "--help"],
          description: "Display help for command",
          priority: 49,
        },
      ],
    },
    {
      name: "share",
      description: "--DEPRECATED-- Move an item to an organization",
      deprecated: true,
      options: [
        {
          name: ["-h", "--help"],
          description: "Display help for command",
          priority: 49,
        },
      ],
      args: [
        { name: "id" },
        { name: "organizationId" },
        { name: "encodedJson", isOptional: true },
      ],
    },
    {
      name: "send",
      description:
        "Work with Bitwarden sends. A Send can be quickly created using this command or subcommands can be used to fine-tune the Send",
      subcommands: [
        {
          name: "list",
          description: "List all the Sends owned by you",
          options: [
            {
              name: ["-h", "--help"],
              description: "Display help for command",
              priority: 49,
            },
          ],
        },
        {
          name: "template",
          description: "Get json templates for send objects",
          options: [
            {
              name: ["-h", "--help"],
              description: "Display help for command",
              priority: 49,
            },
          ],
          args: { name: "object" },
        },
        {
          name: "get",
          description: "Get Sends owned by you",
          options: [
            {
              name: "--output",
              description: "Output directory or filename for attachment",
              args: { name: "output" },
            },
            {
              name: "--text",
              description: "Specifies to return the text content of a Send",
            },
            {
              name: ["-h", "--help"],
              description: "Display help for command",
              priority: 49,
            },
          ],
          args: { name: "id" },
        },
        {
          name: "receive",
          description: "Access a Bitwarden Send from a url",
          options: [
            {
              name: "--password",
              description: "Password needed to access the Send",
              args: { name: "password" },
            },
            {
              name: "--passwordenv",
              description: "Environment variable storing the Send's password",
              args: { name: "passwordenv" },
            },
            {
              name: "--passwordfile",
              description:
                "Path to a file containing the Sends password as its first line",
              args: { name: "passwordfile" },
            },
            {
              name: "--obj",
              description:
                "Return the Send's json object rather than the Send's content",
            },
            {
              name: "--output",
              description: "Specify a file path to save a File-type Send to",
              args: { name: "location" },
            },
            {
              name: ["-h", "--help"],
              description: "Display help for command",
              priority: 49,
            },
          ],
          args: { name: "url" },
        },
        {
          name: "create",
          description: "Create a Send",
          options: [
            {
              name: "--file",
              description:
                "File to Send. Can also be specified in parent's JSON",
              args: { name: "path" },
            },
            {
              name: "--text",
              description:
                "Text to Send. Can also be specified in parent's JSON",
              args: { name: "text" },
            },
            {
              name: "--hidden",
              description:
                "Text hidden flag. Valid only with the --text option",
            },
            {
              name: "--password",
              description:
                "Optional password to access this Send. Can also be specified in JSON",
              args: { name: "password" },
            },
            {
              name: ["-h", "--help"],
              description: "Display help for command",
              priority: 49,
            },
          ],
          args: { name: "encodedJson", isOptional: true },
        },
        {
          name: "edit",
          description: "Edit a Send",
          options: [
            {
              name: "--itemid",
              description: "Overrides the itemId provided in [encodedJson]",
              args: { name: "itemid" },
            },
            {
              name: ["-h", "--help"],
              description: "Display help for command",
              priority: 49,
            },
          ],
          args: { name: "encodedJson", isOptional: true },
        },
        {
          name: "remove-password",
          description: "Removes the saved password from a Send",
          options: [
            {
              name: ["-h", "--help"],
              description: "Display help for command",
              priority: 49,
            },
          ],
          args: { name: "id" },
        },
        {
          name: "delete",
          description: "Delete a Send",
          options: [
            {
              name: ["-h", "--help"],
              description: "Display help for command",
              priority: 49,
            },
          ],
          args: { name: "id" },
        },
        {
          name: "help",
          description: "Display help for command",
          priority: 49,
          args: { name: "command", isOptional: true },
        },
      ],
      options: [
        {
          name: ["-f", "--file"],
          description: "Specifies that <data> is a filepath",
        },
        {
          name: ["-d", "--deleteInDays"],
          description:
            "The number of days in the future to set deletion date, defaults to 7",
          args: { name: "days", default: "7" },
        },
        {
          name: ["-a", "--maxAccessCount"],
          description: "The amount of max possible accesses",
          args: { name: "amount" },
        },
        {
          name: "--hidden",
          description:
            "Hide <data> in web by default. Valid only if --file is not set",
        },
        {
          name: ["-n", "--name"],
          description:
            "The name of the Send. Defaults to a guid for text Sends and the filename for files",
          args: { name: "name" },
        },
        {
          name: "--notes",
          description: "Notes to add to the Send",
          args: { name: "notes" },
        },
        {
          name: "--fullObject",
          description:
            "Specifies that the full Send object should be returned rather than just the access url",
        },
        {
          name: ["-h", "--help"],
          description: "Display help for command",
          priority: 49,
        },
      ],
      args: { name: "data" },
    },
    {
      name: "receive",
      description: "Access a Bitwarden Send from a url",
      options: [
        {
          name: "--password",
          description: "Password needed to access the Send",
          args: { name: "password" },
        },
        {
          name: "--passwordenv",
          description: "Environment variable storing the Send's password",
          args: { name: "passwordenv" },
        },
        {
          name: "--passwordfile",
          description:
            "Path to a file containing the Sends password as its first line",
          args: { name: "passwordfile" },
        },
        {
          name: "--obj",
          description:
            "Return the Send's json object rather than the Send's content",
        },
        {
          name: "--output",
          description: "Specify a file path to save a File-type Send to",
          args: { name: "location" },
        },
        {
          name: ["-h", "--help"],
          description: "Display help for command",
          priority: 49,
        },
      ],
      args: { name: "url" },
    },
    {
      name: "help",
      description: "Display help for command",
      priority: 49,
      args: { name: "command", isOptional: true },
    },
  ],
  options: [
    {
      name: "--pretty",
      description: "Format output. JSON is tabbed with two spaces",
    },
    {
      name: "--raw",
      description: "Return raw output instead of a descriptive message",
    },
    {
      name: "--response",
      description: "Return a JSON formatted version of response output",
    },
    {
      name: "--cleanexit",
      description:
        "Exit with a success exit code (0) unless an error is thrown",
    },
    { name: "--quiet", description: "Don't return anything to stdout" },
    {
      name: "--nointeraction",
      description: "Do not prompt for interactive user input",
    },
    {
      name: "--session",
      description: "Pass session key instead of reading from env",
      args: { name: "session" },
    },
    { name: ["-v", "--version"], description: "Output the version number" },
    {
      name: ["-h", "--help"],
      description: "Display help for command",
      priority: 49,
    },
  ],
};

export default completionSpec;
