// Autogenerated by @fig/complete-commander

import { filepaths } from "@fig/autocomplete-generators";
const bwLogo32x32 = "https://bitwarden.com/images/icon_32x32.png";

const completionSpec: Fig.Spec = {
  name: "bw",
  subcommands: [
    {
      name: "login",
      description: "Log into a user account",
      icon: bwLogo32x32,
      options: [
        {
          name: "--method",
          description: "Two-step login method",
          exclusiveOn: ["--sso", "--apikey", "--check"],
          args: {
            name: "method",
            description: "Authenticator = 0, Email = 1, YubiKey = 3",
            suggestions: [
              { name: "0", description: "Authenticator" },
              { name: "1", description: "Email" },
              { name: "3", description: "YubiKey" },
            ],
          },
        },
        {
          name: "--code",
          description: "Two-step login code",
          exclusiveOn: ["--method", "--apikey", "--check"],
          args: {
            name: "code",
            description: "Valid TOTP Code",
          },
        },
        {
          name: "--sso",
          description: "Log in with Single-Sign On",
          exclusiveOn: [
            "--method",
            "--code",
            "--apikey",
            "--passwordenv",
            "--passwordfile",
            "--check",
          ],
        },
        {
          name: "--apikey",
          description: "Log in with an Api Key",
          exclusiveOn: [
            "--method",
            "--code",
            "--sso",
            "--passwordenv",
            "--passwordfile",
            "--check",
          ],
        },
        {
          name: "--passwordenv",
          description: "Environment variable storing your password",
          exclusiveOn: [
            "--method",
            "--code",
            "--sso",
            "--apikey",
            "--passwordfile",
            "--check",
          ],
          args: {
            name: "passwordenv",
            description: "Environmental Variable Name",
          },
        },
        {
          name: "--passwordfile",
          description:
            "Path to a file containing your password as its first line",
          exclusiveOn: ["--passwordenv", "--sso", "--apikey", "--check"],
          args: {
            name: "passwordfile",
            template: "filepaths",
            description: "Path to a file containing your password",
          },
        },
        {
          name: "--check",
          description: "Check login status",
          exclusiveOn: [
            "--method",
            "--code",
            "--sso",
            "--apikey",
            "--passwordenv",
            "--passwordfile",
          ],
        },
        {
          name: ["-h", "--help"],
          description: "Display help for login command",
          priority: 49,
        },
      ],
      args: [
        {
          name: "email",
          description: "Email Address of Bitwarden Account",
          isOptional: true,
        },
        {
          name: "password",
          description: "Master Password of Bitwarden Vault",
          isOptional: true,
        },
      ],
    },
    {
      name: "logout",
      description: "Log out of the current user account",
      icon: bwLogo32x32,
      options: [
        {
          name: ["-h", "--help"],
          description: "Display help for logout command",
          priority: 49,
        },
      ],
    },
    {
      name: "lock",
      description: "Lock the vault and destroy active session keys",
      icon: bwLogo32x32,
      options: [
        {
          name: ["-h", "--help"],
          description: "Display help for lock command",
          priority: 49,
        },
      ],
    },
    {
      name: "unlock",
      description: "Unlock the vault and return a new session key",
      icon: bwLogo32x32,
      options: [
        {
          name: "--check",
          description: "Check lock status",
          exclusiveOn: ["--passwordenv", "--passwordfile"],
        },
        {
          name: "--passwordenv",
          description: "Supply an environment variable storing your password",
          exclusiveOn: ["--passwordfile"],
          args: {
            name: "passwordenv",
            description: "Environmental variable containing your password",
          },
        },
        {
          name: "--passwordfile",
          description:
            "Path to a file containing your password as its first line",
          exclusiveOn: ["--passwordenv"],
          args: {
            name: "passwordfile",
            description: "File containing your password",
            template: "filepaths",
          },
        },
        {
          name: ["-h", "--help"],
          description: "Display help for unlock command",
          exclusiveOn: ["--check", "--passwordenv", "--passwordfile"],
          priority: 49,
        },
      ],
      args: {
        name: "password",
        description: "Master Password for the Vault to be unlocked",
        isOptional: true,
      },
    },
    {
      name: "sync",
      description: "Pull the latest vault data from server",
      icon: bwLogo32x32,
      options: [
        {
          name: ["-f", "--force"],
          description: "Force a full sync",
          exclusiveOn: ["--last"],
        },
        {
          name: "--last",
          description: "Show details of the last sync",
          exclusiveOn: ["--force", "-f"],
        },
        {
          name: ["-h", "--help"],
          description: "Display help for sync command",
          priority: 49,
        },
      ],
    },
    {
      name: "generate",
      description: "Generate a password/passphrase",
      icon: bwLogo32x32,
      subcommands: [
        {
          name: ["-p", "--passphrase"],
          description: "Generate a passphrase",
          icon: bwLogo32x32,
          priority: 55,
          options: [
            {
              name: "--words",
              description: "Number of words to include in passphrase",
              exclusiveOn: [
                "-u",
                "--uppercase",
                "-l",
                "--lowercase",
                "-n",
                "--number",
                "-s",
                "--special",
                "--length",
                "-h",
                "--help",
              ],
              args: {
                name: "Number of words",
                description: "Number of words to include in passphrase",
              },
            },
            {
              name: ["-c", "--capitalize"],
              exclusiveOn: [
                "-u",
                "--uppercase",
                "-l",
                "--lowercase",
                "-n",
                "--number",
                "-s",
                "--special",
                "--length",
                "-h",
                "--help",
              ],
              description: "Title case passphrase",
            },
            {
              name: "--separator",
              description: "Define word separator",
              insertValue: "--separator '{cursor}'",
              exclusiveOn: [
                "-u",
                "--uppercase",
                "-l",
                "--lowercase",
                "-n",
                "--number",
                "-s",
                "--special",
                "--length",
                "-h",
                "--help",
              ],
              args: {
                name: "separator",
                description:
                  "Character to delineate words in generated passphrase",
              },
            },
            {
              name: "--includeNumber",
              description: "Include a number in output",
              exclusiveOn: [
                "-u",
                "--uppercase",
                "-l",
                "--lowercase",
                "-n",
                "--number",
                "-s",
                "--special",
                "--length",
                "-h",
                "--help",
              ],
            },
          ],
        },
      ],
      options: [
        {
          name: ["-u", "--uppercase"],
          description: "Include uppercase characters",
          exclusiveOn: [
            "-p",
            "--passphrase",
            "--words",
            "-c",
            "--capitalize",
            "--separator",
            "--includeNumber",
            "-h",
            "--help",
          ],
        },
        {
          name: ["-l", "--lowercase"],
          description: "Include lowercase characters",
          exclusiveOn: [
            "-p",
            "--passphrase",
            "--words",
            "-c",
            "--capitalize",
            "--separator",
            "--includeNumber",
            "-h",
            "--help",
          ],
        },
        {
          name: ["-n", "--number"],
          description: "Include numeric characters",
          exclusiveOn: [
            "-p",
            "--passphrase",
            "--words",
            "-c",
            "--capitalize",
            "--separator",
            "--includeNumber",
            "-h",
            "--help",
          ],
        },
        {
          name: ["-s", "--special"],
          description: "Include special characters",
          exclusiveOn: [
            "-p",
            "--passphrase",
            "--words",
            "-c",
            "--capitalize",
            "--separator",
            "--includeNumber",
            "-h",
            "--help",
          ],
        },
        {
          name: "--length",
          description: "Define password length",
          exclusiveOn: [
            "-p",
            "--passphrase",
            "--words",
            "-c",
            "--capitalize",
            "--separator",
            "--includeNumber",
            "-h",
            "--help",
          ],
          args: {
            name: "length",
            description: "Output length",
          },
        },
        {
          name: ["-h", "--help"],
          description: "Display help for generate command",
          exclusiveOn: [
            "-p",
            "--passphrase",
            "--words",
            "-c",
            "--capitalize",
            "--separator",
            "--includeNumber",
            "-u",
            "--uppercase",
            "-l",
            "--lowercase",
            "-n",
            "--number",
            "-s",
            "--special",
            "--length",
          ],
          priority: 49,
        },
      ],
    },
    {
      name: "encode",
      description: "Base 64 encode stdin",
      icon: bwLogo32x32,
      options: [
        {
          name: ["-h", "--help"],
          description: "Display help for encode command",
          priority: 49,
        },
      ],
    },
    {
      name: "config",
      description: "Configure CLI settings",
      icon: bwLogo32x32,
      options: [
        {
          name: "--web-vault",
          description:
            "Provides a custom web vault URL that differs from the base URL",
          args: {
            name: "url",
            description: "URL for a self-hosted Bitwarden Server",
          },
        },
        {
          name: "--api",
          description:
            "Provides a custom API URL that differs from the base URL",
          args: {
            name: "url",
            description: "API URL for a self-hosted Bitwarden Server",
          },
        },
        {
          name: "--identity",
          description:
            "Provides a custom identity URL that differs from the base URL",
          args: {
            name: "url",
            description: "Custom Identity URL that differs from the base URL",
          },
        },
        {
          name: "--icons",
          description:
            "Provides a custom icon service URL that differs from the base URL",
          args: {
            name: "url",
            description:
              "Custom icon service URL that differs from the base URL",
          },
        },
        {
          name: "--notifications",
          description:
            "Provides a custom notifications URL that differs from the base URL",
          args: {
            name: "url",
            description:
              "Custom notifications URL that differs from the base URL",
          },
        },
        {
          name: "--events",
          description:
            "Provides a custom events URL that differs from the base URL",
          args: {
            name: "url",
            description: "Custom events URL that differs from the base URL",
          },
        },
        {
          name: "--key-connector",
          description: "Provides the URL for your Key Connector server",
          args: {
            name: "url",
            description:
              "Custom Key Connector URL that differs from the base URL",
          },
        },
        {
          name: ["-h", "--help"],
          description: "Display help for the config command",
          priority: 49,
        },
      ],
      args: [
        {
          name: "setting",
          description: "Setting to configure",
          suggestions: ["server"],
        },
        {
          name: "value",
          description: "Value to set",
        },
      ],
    },
    {
      name: "update",
      description: "Check for updates",
      icon: bwLogo32x32,
      options: [
        {
          name: ["-h", "--help"],
          description: "Display help for update command",
          priority: 49,
        },
      ],
    },
    {
      name: "completion",
      description: "Generate shell completions",
      icon: bwLogo32x32,
      options: [
        {
          name: "--shell",
          description: "Shell to generate completions for",
          args: {
            name: "shell",
            suggestions: ["zsh"],
            description: "Shell to generate completions for",
            default: "zsh",
          },
        },
        {
          name: ["-h", "--help"],
          description: "Display help for completion command",
          priority: 49,
        },
      ],
    },
    {
      name: "status",
      description:
        "Show server details, last sync time & date, user information, and vault status",
      icon: bwLogo32x32,
      options: [
        {
          name: ["-h", "--help"],
          description: "Display help for status command",
          priority: 49,
        },
      ],
    },
    {
      name: "serve",
      description: "Start a RESTful API webserver",
      icon: bwLogo32x32,
      options: [
        {
          name: "--hostname",
          description: "The hostname to bind your API webserver to",
          args: { name: "hostname" },
        },
        {
          name: "--port",
          description: "The port to run your API webserver on",
          args: { name: "port" },
        },
        {
          name: ["-h", "--help"],
          description: "Display help for serve command",
          priority: 49,
        },
      ],
    },
    {
      name: "list",
      description:
        "Retrieves an array of objects (items, folders, collections, org-collections, org-members, organizations) from your Vault",
      icon: bwLogo32x32,
      options: [
        {
          name: "--search",
          description: "Perform a search on the listed objects",
          args: { name: "search" },
        },
        {
          name: "--url",
          description: "Filter items of type login with a url-match search",
          args: { name: "url" },
        },
        {
          name: "--folderid",
          description: "Filter items by folder id",
          args: { name: "folderid" },
        },
        {
          name: "--collectionid",
          description: "Filter items by collection id",
          args: { name: "collectionid" },
        },
        {
          name: "--organizationid",
          description: "Filter items or collections by organization id",
          args: { name: "organizationid" },
        },
        {
          name: "--trash",
          description: "Filter items that are in the trash",
        },
        {
          name: ["-h", "--help"],
          description: "Display help for the list command",
          priority: 49,
        },
      ],
      args: {
        name: "object",
        suggestions: [
          "items",
          "folders",
          "collections",
          "org-collections",
          "org-members",
          "organizations",
        ],
      },
    },
    {
      name: "get",
      description: "Get an object from the vault",
      icon: bwLogo32x32,
      subcommands: [
        {
          name: "template",
          description: "Type of template to get",
          args: {
            name: "object",
            suggestions: [
              "item",
              "item.field",
              "item.login",
              "item.login.uri",
              "item.card",
              "item.identity",
              "item.securenote",
              "folder",
              "collection",
              "item-collections",
              "org-collection",
              "send.text",
              "send.file",
            ],
          },
        },
        {
          name: "attachment",
          options: [
            {
              name: "--itemid",
              description: "Vault Item ID containing attachment",
              args: {
                name: "itemid",
                description: "ID of Vault Item containing attachment",
              },
              isRequired: true,
            },
            {
              name: "--output",
              description: "Output directory and/or filename",
              args: {
                name: "output",
                description: "Output directory and/or filename",
                template: "folders",
              },
            },
          ],
        },
      ],
      options: [
        {
          name: "--id",
          description: "Exact id of the object",
          args: {
            name: "id",
            description: "Object id",
          },
        },
        {
          name: "--organizationid",
          description: "Organization id for an organization object",
          args: {
            name: "organizationid",
            description: "Organization id",
          },
        },
        {
          name: ["-h", "--help"],
          description: "Display help for the get command",
          priority: 49,
        },
      ],
      args: [
        {
          name: "object",
          suggestions: [
            "item",
            "username",
            "password",
            "uri",
            "totp",
            "exposed",
            "folder",
            "collection",
          ],
          description: "Type of object to get from the Vault",
        },
        {
          name: "id",
          description: "Search term or object's globally unique id",
        },
      ],
    },
    {
      name: "create",
      description: "Create an object in the vault",
      icon: bwLogo32x32,
      options: [
        {
          name: "--file",
          description: "Path to file for attachment",
          args: {
            name: "file",
            description: "File to attach",
            template: "filepaths",
          },
        },
        {
          name: "--itemid",
          description: "Attachment's item id",
          args: {
            name: "itemid",
            description: "Item ID",
          },
        },
        {
          name: "--organizationid",
          description: "Organization id for an organization object",
          args: {
            name: "organizationid",
            description: "Organization ID",
          },
        },
        {
          name: ["-h", "--help"],
          description: "Display help for the create command",
          priority: 49,
        },
      ],
      args: [
        {
          name: "object",
          description: "Object to be created",
          suggestions: ["item", "attachment", "folder", "org-collection"],
        },
        {
          name: "encodedJson",
          description: "Encoded Json instead of uploading to Vault",
        },
      ],
    },
    {
      name: "edit",
      description: "Edit an object from the vault",
      icon: bwLogo32x32,
      options: [
        {
          name: "--organizationid",
          description: "Organization id for an organization object",
          args: {
            name: "organizationid",
            description: "Organization ID",
          },
        },
        {
          name: ["-h", "--help"],
          description: "Display help for the edit command",
          priority: 49,
        },
      ],
      args: [
        {
          name: "object",
          description: "Type of Vault Object to edit",
          suggestions: ["item", "item-collections", "folder", "org-collection"],
        },
        {
          name: "id",
          description: "Object's globally unique id",
        },
        {
          name: "encodedJson",
          isOptional: true,
          description: "Encoded json of the object to create",
        },
      ],
    },
    {
      name: "delete",
      description: "Delete an object from the vault",
      icon: bwLogo32x32,
      isDangerous: true,
      options: [
        {
          name: "--itemid",
          description: "Attachment's item id",
          args: { name: "itemid", description: "Item Id" },
          isDangerous: true,
        },
        {
          name: "--organizationid",
          description: "Organization id for an organization object",
          args: { name: "organizationid", description: "Organization Id" },
          isDangerous: true,
        },
        {
          name: ["-p", "--permanent"],
          description:
            "Permanently deletes the item instead of soft-deleting it (item only)",
          isDangerous: true,
        },
        {
          name: ["-h", "--help"],
          description: "Display help for the delete command",
          exclusiveOn: ["--itemid", "--organizationid", "-p", "--permanent"],
          priority: 49,
        },
      ],
      args: [
        {
          name: "object",
          description: "Object to delete",
          suggestions: ["item", "attachment", "folder", "org-collection"],
        },
        {
          name: "id",
          description: "Unique Vault ID",
        },
      ],
    },
    {
      name: "restore",
      description: "Restores an object from the trash",
      icon: bwLogo32x32,
      options: [
        {
          name: ["-h", "--help"],
          description: "Display help for the restore command",
          priority: 49,
        },
      ],
      args: [{ name: "object" }, { name: "id" }],
    },
    {
      name: "move",
      description: "Transfers a Vault item to an Organization",
      icon: bwLogo32x32,
      options: [
        {
          name: ["-h", "--help"],
          description: "Display help for the move command",
          priority: 49,
        },
      ],
      args: [
        { name: "id" },
        { name: "organizationId" },
        { name: "encodedJson", isOptional: true },
      ],
    },
    {
      name: "confirm",
      description: "Confirm an object to the organization",
      icon: bwLogo32x32,
      options: [
        {
          name: "--organizationid",
          description: "Organization id for an organization object",
          args: {
            name: "organizationid",
            description: "Organization ID",
          },
        },
        {
          name: ["-h", "--help"],
          description: "Display help for the confirm command",
          priority: 49,
        },
      ],
      args: [
        {
          name: "object",
          description: "Valid objects are: org-member",
        },
        {
          name: "id",
          description: "Organization id for an organization object",
        },
      ],
    },
    {
      name: "import",
      description: "Import vault data from a file",
      icon: bwLogo32x32,
      options: [
        {
          name: "--formats",
          description: "List supported file formats",
        },
        {
          name: "--organizationid",
          description: "ID of the organization to import to",
          args: {
            name: "organizationid",
            description: "Organization ID to be imported to",
          },
        },
        {
          name: ["-h", "--help"],
          description: "Display help for the import command",
          priority: 49,
        },
      ],
      args: [
        {
          name: "format",
          suggestions: [
            "1password1pif",
            "1password1pux",
            "1passwordmaccsv",
            "1passwordwincsv",
            "ascendocsv",
            "avastcsv",
            "avastjson",
            "aviracsv",
            "bitwardencsv",
            "bitwardenjson",
            "blackberrycsv",
            "blurcsv",
            "buttercupcsv",
            "chromecsv",
            "clipperzhtml",
            "codebookcsv",
            "dashlanecsv",
            "dashlanejson",
            "encryptrcsv",
            "enpasscsv",
            "enpassjson",
            "firefoxcsv",
            "fsecurefsk",
            "gnomejson",
            "kasperskytxt",
            "keepass2xml",
            "keepassxcsv",
            "keepercsv",
            "lastpasscsv",
            "logmeoncecsv",
            "meldiumcsv",
            "msecurecsv",
            "mykicsv",
            "nordpasscsv",
            "operacsv",
            "padlockcsv",
            "passboltcsv",
            "passkeepcsv",
            "passmanjson",
            "passpackcsv",
            "passwordagentcsv",
            "passwordbossjson",
            "passworddragonxml",
            "passwordwallettxt",
            "pwsafexml",
            "remembearcsv",
            "roboformcsv",
            "safaricsv",
            "safeincloudxml",
            "saferpasscsv",
            "securesafecsv",
            "splashidcsv",
            "stickypasswordxml",
            "truekeycsv",
            "upmcsv",
            "vivaldicsv",
            "yoticsv",
            "zohovaultcsv",
          ],
          description: "Format of import file",
          default: "bitwardenjson",
        },
        {
          name: "input",
          template: "filepaths",
          description: "File to be imported",
        },
      ],
    },
    {
      name: "export",
      description: "Export vault data to a CSV or JSON file",
      icon: bwLogo32x32,
      options: [
        {
          name: "--output",
          description: "Set output directory or filename",
          args: {
            name: "output",
            template: "folders",
            description: "Path to export to",
          },
        },
        {
          name: "--format",
          description: "Export file format",
          args: {
            name: "format",
            suggestions: ["csv", "json", "encrypted_json"],
            description: "Export format",
            default: "json",
          },
        },
        {
          name: "--password",
          description:
            "Use a password to encrypt instead of your Bitwarden account encryption key. Only applies to the encrypted_json format",
          args: {
            name: "password",
            isOptional: true,
            description: "Password that will encrypt this export",
          },
        },
        {
          name: "--organizationid",
          description: "Enter organization id for an organization",
          args: {
            name: "organizationid",
            description: "Organization id",
          },
        },
        {
          name: ["-h", "--help"],
          description: "Display help for the export command",
          priority: 49,
        },
      ],
    },
    {
      name: "share",
      description: "--DEPRECATED-- Move an item to an organization",
      icon: "fig://icon?type=alert",
      deprecated: {
        insertValue: "move",
        description: "--DEPRECATED-- Use bw MOVE instead",
      },
      isDangerous: true,
      options: [
        {
          name: ["-h", "--help"],
          description: "Display help for the share command",
          priority: 55,
        },
      ],
      args: [
        {
          name: "id",
          description: "Object's globally unique ID",
        },
        {
          name: "organizationId",
          description: "Organization's globally unique ID",
        },
        {
          name: "encodedJson",
          description:
            "Encoded json of an array of collection ids. Can also be piped into stdin",
          isOptional: true,
        },
      ],
    },
    {
      name: "send",
      description:
        "Work with Bitwarden Sends. A Send can be quickly created using this command or subcommands can be used to fine-tune the Send",
      icon: bwLogo32x32,
      subcommands: [
        {
          name: "list",
          description: "List all the Sends owned by you",
          icon: bwLogo32x32,
          options: [
            {
              name: ["-h", "--help"],
              description: "Display help for the Send command",
              //priority: 49,
            },
          ],
        },
        {
          name: "template",
          description: "Get json templates for Send objects",
          icon: bwLogo32x32,
          options: [
            {
              name: ["-h", "--help"],
              description: "Display help for the template sub-command",
              priority: 49,
            },
          ],
          args: {
            name: "object",
            description: "Json template to fetch",
            suggestions: ["send.text", "send.file"],
          },
        },
        {
          name: "get",
          description: "Get Sends owned by you",
          icon: bwLogo32x32,
          options: [
            {
              name: "--output",
              description: "Output directory or filename for attachment",
              args: {
                name: "output",
                description: "",
                template: "folders",
              },
            },
            {
              name: "--text",
              description: "Specifies to return the text content of a Send",
            },
            {
              name: ["-h", "--help"],
              description: "Display help for the Send get sub-command",
              //priority: 49,
            },
          ],
          args: {
            name: "Send ID",
            description: "Send ID",
          },
        },
        {
          name: "receive",
          description: "Access a Bitwarden Send from a url",
          icon: bwLogo32x32,
          options: [
            {
              name: "--password",
              description: "Password needed to access the Send",
              exclusiveOn: ["--passwordenv", "--passwordfile"],
              args: {
                name: "password",
                description: "Password for Send",
              },
            },
            {
              name: "--passwordenv",
              description: "Environment variable storing the Send's password",
              exclusiveOn: ["--password", "--passwordfile"],
              args: {
                name: "passwordenv",
                description: "Environment variable containing Send's password",
              },
            },
            {
              name: "--passwordfile",
              description:
                "Path to a file containing the Send's password as its first line",
              exclusiveOn: ["--passwordenv", "--password"],
              args: {
                name: "passwordfile",
                description: "File containing Send's password",
                template: "filepaths",
              },
            },
            {
              name: "--obj",
              description:
                "Return the Send's json object rather than the Send's content",
            },
            {
              name: "--output",
              description: "Specify a file path to save a File-type Send to",
              args: {
                name: "location",
                description: "Path to save File-type Send",
                template: "folders",
              },
            },
            {
              name: ["-h", "--help"],
              description: "Display help for the receive sub-command",
              priority: 49,
            },
          ],
          args: {
            name: "Send URL",
            description: "URL of Send to download",
          },
        },
        {
          name: "create",
          description: "Create a Send",
          icon: bwLogo32x32,
          options: [
            {
              name: "--file",
              description:
                "File to Send. Can also be specified in parent's JSON",
              exclusiveOn: ["--text", "--hidden"],
              args: {
                name: "path",
                description: "Path to file to attach as content",
                template: "filepaths",
              },
            },
            {
              name: "--text",
              description:
                "Text to Send. Can also be specified in parent's JSON",
              exclusiveOn: ["--file"],
              args: {
                name: "text",
                description: "Text to include as content",
              },
            },
            {
              name: "--hidden",
              dependsOn: ["--text"],
              description:
                "Text hidden flag. Valid only with the --text option",
            },
            {
              name: "--password",
              description:
                "Optional password to access this Send. Can also be specified in JSON",
              args: {
                name: "password",
                description: "Password to secure the Send",
              },
            },
            {
              name: ["-h", "--help"],
              description: "Display help for the create sub-command",
              priority: 49,
            },
          ],
          args: {
            name: "encodedJson",
            description: "Encoded Json to be uploaded",
          },
        },
        {
          name: "edit",
          description: "Edit a Send",
          icon: bwLogo32x32,
          options: [
            {
              name: "--itemid",
              description: "Overrides the itemId provided in [encodedJson]",
              args: {
                name: "itemid",
                description: "ItemID",
              },
            },
            {
              name: ["-h", "--help"],
              description: "Display help for the edit sub-command",
              priority: 49,
            },
          ],
          args: {
            name: "encodedJson",
            description: "Encoded Json",
          },
        },
        {
          name: "remove-password",
          description: "Removes the saved password from a Send",
          icon: bwLogo32x32,
          options: [
            {
              name: ["-h", "--help"],
              description: "Display help for the remove-password sub-command",
              priority: 49,
            },
          ],
          args: {
            name: "Send ID",
            description: "ID of the Send to remove password from",
          },
        },
        {
          name: "delete",
          description: "Delete a Send",
          icon: bwLogo32x32,
          options: [
            {
              name: ["-h", "--help"],
              description: "Display help for the delete sub-command",
              priority: 49,
            },
          ],
          args: {
            name: "Send ID",
            description: "ID of the Send to delete",
          },
        },
        {
          name: "help",
          description: "Display help for the Send command",
          priority: 49,
          args: { name: "command", isOptional: true },
        },
      ],
      options: [
        {
          name: ["-f", "--file"],
          description: "Specifies that <data> is a filepath",
        },
        {
          name: ["-d", "--deleteInDays"],
          description:
            "The number of days in the future to set deletion date (defaults to 7 if not specified)",
          args: {
            name: "days",
            default: "7",
            isOptional: true,
          },
        },
        {
          name: ["-a", "--maxAccessCount"],
          description: "The max number of accesses allowed for this Send",
          args: {
            name: "amount",
            description: "Max number of accesses allowed",
          },
        },
        {
          name: "--hidden",
          description:
            "Hide <data> in web by default. Valid only if --file is not set",
        },
        {
          name: ["-n", "--name"],
          description:
            "The name of the Send. Defaults to a guid for text Sends and the filename for files",
          args: {
            name: "name",
            description: "Send name",
          },
        },
        {
          name: "--notes",
          description: "Notes to add to the Send",
          args: {
            name: "notes",
            description: "Notes to add to the Send",
          },
        },
        {
          name: "--fullObject",
          description:
            "Specifies that the full Send object should be returned rather than just the access url",
        },
        {
          name: ["-h", "--help"],
          description: "Display help for the Send command",
          priority: 49,
        },
      ],
      args: {
        name: "data",
        description: "Encoded Json data",
      },
    },
    {
      name: "device-approval",
      description:
        "Manage device approval requests sent to organizations that use SSO with trusted devices",
      icon: bwLogo32x32,
      subcommands: [
        {
          name: "list",
          description: "List all pending requests for an organisation",
          icon: bwLogo32x32,
          options: [
            {
              name: ["-h", "--help"],
              description: "Display help for the list sub-command",
              priority: 1,
            },
            {
              name: "--organizationid",
              description: "The organisation id (required)",
              args: {
                name: "organizationid",
                description: "Organisation ID",
              },
              priority: 100,
            },
          ],
        },
        {
          name: "approve",
          description: "Approve a pending request",
          icon: bwLogo32x32,
          options: [
            {
              name: ["-h", "--help"],
              description: "Display help for the approve sub-command",
              priority: 49,
            },
            {
              name: "requestId",
              description: "The id of the request to approve",
              args: {
                name: "requestId",
                description: "The id of the request to approve",
                isVariadic: true,
              },
            },
            {
              name: "--organizationid",
              description: "The organisation id (required)",
              args: {
                name: "organizationid",
                description: "Organisation ID",
              },
              priority: 100,
            },
          ],
        },
        {
          name: "approve-all",
          description: "Approve all pending requests for an organisation",
          icon: "fig://icon?type=alert",
          isDangerous: true,
          options: [
            {
              name: ["-h", "--help"],
              description: "Display help for the approve-all sub-command",
              priority: 49,
            },
            {
              name: "--organizationid",
              description: "The organisation id (required)",
              args: {
                name: "organizationid",
                description: "Organisation ID",
              },
              priority: 100,
            },
          ],
        },
        {
          name: "deny",
          description: "Deny a pending request",
          icon: bwLogo32x32,
          options: [
            {
              name: ["-h", "--help"],
              description: "Display help for the deny sub-command",
              priority: 49,
            },
            {
              name: "requestId",
              description: "The id of the request to deny",
              args: {
                name: "requestId",
                description: "The id of the request to approve",
                isVariadic: true,
              },
            },
            {
              name: "--organizationid",
              description: "The organisation id (required)",
              args: {
                name: "organizationid",
                description: "Organisation ID",
              },
              priority: 100,
            },
          ],
        },
        {
          name: "deny-all",
          description: "Deny all pending requests for an organisation",
          icon: bwLogo32x32,
          options: [
            {
              name: ["-h", "--help"],
              description: "Display help for the deny-all sub-command",
              priority: 49,
            },
            {
              name: "--organizationid",
              description: "The organisation id (required)",
              args: {
                name: "organizationid",
                description: "Organisation ID",
              },
              priority: 100,
            },
          ],
        },
        {
          name: "help",
          description: "Display help for command",
          priority: 49,
          args: { name: "command", isOptional: true },
        },
      ],
    },
    {
      name: "receive",
      description: "Access a Bitwarden Send from a url",
      icon: bwLogo32x32,
      options: [
        {
          name: "--password",
          description: "Password needed to access the Send",
          exclusiveOn: ["--passwordenv", "--passwordfile"],
          args: {
            name: "password",
            description: "Password for Send",
          },
        },
        {
          name: "--passwordenv",
          description: "Environment variable storing the Send's password",
          exclusiveOn: ["--password", "--passwordfile"],
          args: {
            name: "passwordenv",
            description: "Environment variable containing Send's password",
          },
        },
        {
          name: "--passwordfile",
          description:
            "Path to a file containing the Send's password as its first line",
          exclusiveOn: ["--passwordenv", "--password"],
          args: {
            name: "passwordfile",
            description: "File containing Send's password",
            template: "filepaths",
          },
        },
        {
          name: "--obj",
          description:
            "Return the Send's json object rather than the Send's content",
        },
        {
          name: "--output",
          description: "Specify a file path to save a File-type Send to",
          args: {
            name: "location",
            description: "Path to save File-type Send",
            template: "folders",
          },
        },
        {
          name: ["-h", "--help"],
          description: "Display help for the receive sub-command",
          priority: 49,
        },
      ],
      args: {
        name: "Send URL",
        description: "URL of Send to download",
      },
    },
    {
      name: "help",
      description: "Display help for the Bitwarden CLI tool",
      icon: bwLogo32x32,
      priority: 49,
      args: {
        name: "command",
        description: "Subcommand to display help for",
        suggestions: [
          "login",
          "logout",
          "lock",
          "unlock",
          "sync",
          "generate",
          "encode",
          "config",
          "update",
          "completion",
          "status",
          "serve",
          "list",
          "get",
          "create",
          "edit",
          "delete",
          "restore",
          "move",
          "confirm",
          "import",
          "export",
          "share",
          "send",
          "receive",
          "device-approval",
        ],
        isOptional: true,
      },
    },
  ],
  options: [
    {
      name: "--pretty",
      description: "Format output. JSON is tabbed with two spaces",
      isPersistent: true,
      icon: "fig://icon?type=asterisk",
      priority: 40,
    },
    {
      name: "--raw",
      description: "Return raw output instead of a descriptive message",
      isPersistent: true,
      icon: "fig://icon?type=asterisk",
      priority: 40,
    },
    {
      name: "--response",
      description: "Return a JSON formatted version of response output",
      isPersistent: true,
      icon: "fig://icon?type=asterisk",
      priority: 40,
    },
    {
      name: "--cleanexit",
      description:
        "Exit with a success exit code (0) unless an error is thrown",
      isPersistent: true,
      icon: "fig://icon?type=asterisk",
      priority: 40,
    },
    {
      name: "--quiet",
      description: "Don't return anything to stdout",
      isPersistent: true,
      icon: "fig://icon?type=asterisk",
      priority: 40,
    },
    {
      name: "--nointeraction",
      description: "Do not prompt for interactive user input",
      isPersistent: true,
      icon: "fig://icon?type=asterisk",
      priority: 40,
    },
    {
      name: "--session",
      description: "Pass session key instead of reading from env",
      args: {
        name: "session",
        description: "Session Key",
      },
      isPersistent: true,
      icon: "fig://icon?type=asterisk",
      priority: 40,
    },
    {
      name: ["-v", "--version"],
      description: "Output BW CLI tool version number",
      icon: "fig://icon?type=asterisk",
      priority: 40,
    },
    {
      name: ["-h", "--help"],
      description: "Display help for command",
      icon: "fig://icon?type=asterisk",
      priority: 49,
    },
  ],
};

export default completionSpec;
