const completionSpec: Fig.Spec = {
  name: "rustup",
  description: "The Rust toolchain installer",
  subcommands: [
    {
      name: "show",
      description: "Show the active and installed toolchains or profiles",
      subcommands: [
        {
          name: "active-toolchain",
          description: "Show the active toolchain",
        },
        {
          name: "home",
          description: "Display the computed value of RUSTUP_HOME",
        },
        {
          name: "profile",
          description: "Show the current profile",
        },
        {
          name: "keys",
          description: "Display the known PGP keys",
        },
        {
          name: "help",
          description:
            "Prints this message or the help of the given subcommand(s)",
        },
      ],
      options: [
        {
          name: ["-h", "--help"],
          description: "Prints help information",
        },
      ],
    },
    {
      name: "update",
      description: "Update Rust toolchains and rustup",
      options: [
        {
          name: "--force",
          description: "Force an update, even if some components are missing",
        },
        {
          name: "--force-non-host",
          description:
            "Install toolchains that require an emulator. See https://github.com/rust-lang/rustup/wiki/Non-host-toolchains",
        },
        {
          name: ["-h", "--help"],
          description: "Prints help information",
        },
        {
          name: "--no-self-update",
          description:
            "Don't perform self update when running the `rustup update` command",
        },
      ],
      args: {
        name: "toolchain",
        description:
          "Toolchain name, such as 'stable', 'nightly', or '1.8.0'. For more information see `rustup help toolchain`",
        isOptional: true,
      },
    },
    {
      name: "check",
      description: "Check for updates to Rust toolchains and rustup",
      options: [
        {
          name: ["-h", "--help"],
          description: "Prints help information",
        },
      ],
      args: {
        name: "toolchain",
        description:
          "Toolchain name, such as 'stable', 'nightly', or '1.8.0'. For more information see `rustup help toolchain`",
        isOptional: true,
      },
    },
    {
      name: "default",
      description:
        "Sets the default toolchain to the one specified. If the toolchain is not already installed then it is installed first",
      options: [
        {
          name: ["-h", "--help"],
          description: "Prints help information",
        },
      ],
    },
    {
      name: "target",
      description: "Modify a toolchain's supported targets",
      options: [
        {
          name: ["-h", "--help"],
          description: "Prints help information",
        },
      ],
      subcommands: [
        {
          name: "list",
          description: "List installed and available targets",
          options: [
            {
              name: ["-h", "--help"],
              description: "Prints help information",
            },
            {
              name: ["-V", "--version"],
              description: "Prints version information",
            },
          ],
        },
        {
          name: "add",
          description: "Add a target to a Rust toolchain",
          options: [
            {
              name: ["-h", "--help"],
              description: "Prints help information",
            },
            {
              name: ["-V", "--version"],
              description: "Prints version information",
            },
            {
              name: "--toolchain",
              args: {
                name: "<toolchain",
                description:
                  "Toolchain name, such as 'stable', 'nightly', or '1.8.0'",
              },
            },
          ],
        },
        {
          name: "remove",
          options: [
            {
              name: ["-h", "--help"],
              description: "Prints help information",
            },
            {
              name: ["-V", "--version"],
              description: "Prints version information",
            },
            {
              name: "--toolchain",
              args: {
                name: "<toolchain",
                description:
                  "Toolchain name, such as 'stable', 'nightly', or '1.8.0'",
              },
            },
          ],
          description: "Remove a target from a Rust toolchain",
        },
        {
          name: "help",
          options: [
            {
              name: ["-h", "--help"],
              description: "Prints help information",
            },
            {
              name: ["-V", "--version"],
              description: "Prints version information",
            },
          ],
          description:
            "Prints this message or the help of the given subcommand(s)",
          args: {
            name: "subcommand",
            isOptional: true,
          },
        },
      ],
    },
    {
      name: "toolchain",
      description: "Modify or query the installed toolchains",
      options: [
        {
          name: ["-h", "--help"],
          description: "Prints help information",
        },
      ],
      subcommands: [
        {
          name: "list",
          options: [
            {
              name: ["-h", "--help"],
              description: "Prints help information",
            },
            {
              name: ["-V", "--version"],
              description: "Prints version information",
            },
          ],
          description: "List installed toolchains",
        },
        {
          name: "install",
          options: [
            {
              name: ["-h", "--help"],
              description: "Prints help information",
            },
            {
              name: ["-t", "--target"],
              description: "Add specific targets on installation",
              args: {
                name: "<targets>",
                isVariadic: true,
              },
            },
            {
              name: ["-c", "--component"],
              description: "Add specific components on installation",
              args: {
                name: "<components>",
                isVariadic: true,
              },
            },
            {
              name: "--profile",
              args: {
                name: "<profile>",
                suggestions: ["minimal", "default", "complete"],
              },
            },
            {
              name: "--allow-downgrade",
              description:
                "Allow rustup to downgrade the toolchain to satisfy your component choice",
            },
            {
              name: "--force",
              description:
                "Force an update, even if some components are missing",
            },
            {
              name: "--no-self-update",
              description:
                "Don't perform self update when running the`rustup toolchain install` command",
            },
          ],
          args: {
            name: "<toolchain>",
            description:
              "Toolchain name, such as 'stable', 'nightly', or '1.8.0'",
            isVariadic: true,
          },
          description: "Install or update a given toolchain",
        },
        {
          name: "uninstall",
          options: [
            {
              name: ["-h", "--help"],
              description: "Prints help information",
            },
          ],
          args: {
            name: "<toolchain>",
            description:
              "Toolchain name, such as 'stable', 'nightly', or '1.8.0'",
            isVariadic: true,
          },
          description: "Uninstall a toolchain",
        },
        {
          name: "link",
          options: [
            {
              name: ["-h", "--help"],
              description: "Prints help information",
            },
          ],
          args: [
            {
              name: "<toolchain>",
              description: "Custom toolchain name",
              isVariadic: true,
            },
            {
              name: "<path>",
              description: "Path to the directory",
            },
          ],
          description: "Create a custom toolchain by symlinking to a directory",
        },
        {
          name: "help",
          options: [
            {
              name: ["-h", "--help"],
              description: "Prints help information",
            },
            {
              name: ["-V", "--version"],
              description: "Prints version information",
            },
          ],
          description:
            "Prints this message or the help of the given subcommand(s)",
          args: {
            name: "subcommand",
            isOptional: true,
          },
        },
      ],
    },
    {
      name: "component",
      description: "Modify a toolchain's installed components",
      options: [
        {
          name: ["-h", "--help"],
          description: "Prints help information",
        },
      ],
      subcommands: [
        {
          name: "list",
          options: [
            {
              name: ["-h", "--help"],
              description: "Prints help information",
            },
            {
              name: ["-V", "--version"],
              description: "Prints version information",
            },
          ],
          description: "List installed and available components",
        },
        {
          name: "add",
          options: [
            {
              name: ["-h", "--help"],
              description: "Prints help information",
            },
            {
              name: ["-V", "--version"],
              description: "Prints version information",
            },
          ],
          description: "Add a component to a Rust toolchain",
        },
        {
          name: "remove",
          options: [
            {
              name: ["-h", "--help"],
              description: "Prints help information",
            },
            {
              name: ["-V", "--version"],
              description: "Prints version information",
            },
          ],
          description: "Remove a component from a Rust toolchain",
        },
        {
          name: "help",
          description:
            "Prints this message or the help of the given subcommand(s)",
          args: {
            name: "subcommand(s)",
            isOptional: true,
          },
        },
      ],
    },
    {
      name: "override",
      description: "Modify directory toolchain overrides",
      options: [
        {
          name: ["-h", "--help"],
          description: "Prints help information",
        },
      ],
      subcommands: [
        {
          name: "list",
          options: [
            {
              name: ["-h", "--help"],
              description: "Prints help information",
            },
            {
              name: ["-V", "--version"],
              description: "Prints version information",
            },
          ],
          description: "List directory toolchain overrides",
        },
        {
          name: "set",
          options: [
            {
              name: ["-h", "--help"],
              description: "Prints help information",
            },
            {
              name: ["-V", "--version"],
              description: "Prints version information",
            },
          ],
          description: "Set the override toolchain for a directory",
        },
        {
          name: "unset",
          options: [
            {
              name: ["-h", "--help"],
              description: "Prints help information",
            },
            {
              name: ["-V", "--version"],
              description: "Prints version information",
            },
          ],
          description: "Remove the override toolchain for a directory",
        },
        {
          name: "help",
          description:
            "Prints this message or the help of the given subcommand(s)",
          args: {
            name: "subcommand(s)",
            isOptional: true,
          },
        },
      ],
    },
    {
      name: "run",
      description:
        "Run a command with an environment configured for a given toolchain",
      options: [
        {
          name: ["-h", "--help"],
          description: "Prints help information",
        },
        {
          name: "--install",
          description: "Install the requested toolchain if needed",
        },
      ],
      args: [
        {
          name: "<toolchain>",
          description:
            "Toolchain name, such as 'stable', 'nightly', or '1.8.0'",
        },
        {
          name: "<command>",
          isVariadic: true,
          isCommand: true,
        },
      ],
    },
    {
      name: "which",
      description: "Display which binary will be run for a given command",
      options: [
        {
          name: ["-h", "--help"],
          description: "Prints help information",
        },
        {
          name: "--toolchain",
          description:
            "Toolchain name, such as 'stable', 'nightly', or '1.8.0'",
          args: {
            name: "<toolchain>",
            description:
              "Toolchain name, such as 'stable', 'nightly', or '1.8.0'",
          },
        },
      ],
    },
    {
      name: "doc",
      description: "Open the documentation for the current toolchain",
      options: [
        {
          name: "--alloc",
          description: "The Rust core allocation and collections library",
        },
        {
          name: "--book",
          description: "The Rust Programming Language book",
        },
        {
          name: "--cargo",
          description: "The Cargo Book",
        },
        {
          name: "--core",
          description: "The Rust Core Library",
        },
        {
          name: "--edition-guide",
          description: "The Rust Edition Guide",
        },
        {
          name: "--embedded-book",
          description: "The Embedded Rust Book",
        },
        {
          name: ["-h", "--help"],
          description: "Prints help information",
        },
        {
          name: "--nomicon",
          description: "The Dark Arts of Advanced and Unsafe Rust Programming",
        },
        {
          name: "--path",
          description: "Only print the path to the documentation",
        },
        {
          name: "--proc_macro",
          description:
            "A support library for macro authors when defining new macros",
        },
        {
          name: "--reference",
          description: "The Rust Reference",
        },
        {
          name: "--rust-by-example",
          description:
            "A collection of runnable examples that illustrate various Rust concepts and standard libraries",
        },
        {
          name: "--rustc",
          description: "The compiler for the Rust programming language",
        },
        {
          name: "--rustdoc",
          description: "Generate documentation for Rust projects",
        },
        {
          name: "--std",
          description: "Standard library API documentation",
        },
        {
          name: "--test",
          description:
            "Support code for rustc's built in unit-test and micro-benchmarking framework",
        },
        {
          name: "--unstable-book",
          description: "--unstable-book",
        },
        {
          name: "--toolchain",
          description:
            "Toolchain name, such as 'stable', 'nightly', or '1.8.0'",
          args: {
            name: "<toolchain>",
          },
        },
      ],
      args: {
        name: "<topic>",
        description:
          "Topic such as 'core', 'fn', 'usize', 'eprintln!', 'core::arch', 'alloc::format!', 'std::fs', 'std::fs::read_dir', 'std::io::Bytes', 'std::iter::Sum', 'std::io::error::Result' etc",
        suggestions: [
          "std::prim_bool",
          "std::try",
          "std::all",
          "std::print!",
          "std::is_x86_feature_detected",
          "std::hint",
          "std::hint::black_box",
          "std::hint::unreachable_unchecked",
          "std::hint::spin_loop",
          "std::format!",
          "std::llvm_asm!",
          "std::print",
          "std::thread_local",
          "std::assert_ne!",
          "std::assert_matches::debug_assert_matches",
          "std::assert_matches",
          "std::assert_matches::assert_matches",
          "std::assert_matches::debug_assert_matches!",
          "std::assert_matches::assert_matches!",
          "std::i128",
          "std::u32",
          "std::ascii",
          "std::ascii::AsciiExt",
          "std::ascii::EscapeDefault",
          "std::ascii::escape_default",
          "std::u64",
          "std::u64::MAX",
          "std::u64::MIN",
          "std::cmp::Ord!",
          "std::cmp::Ord",
          "std::cmp::Eq",
          "std::cmp::PartialEq",
          "std::cmp::PartialOrd",
          "std::cmp",
          "std::cmp::max_by",
          "std::cmp::PartialEq!",
          "std::cmp::Eq!",
          "std::cmp::Ord",
          "std::cmp::max_by_key",
          "std::cmp::PartialOrd!",
          "std::cmp::Eq",
          "std::cmp::Ordering",
          "std::cmp::Reverse",
          "std::cmp::min_by",
          "std::cmp::PartialOrd",
          "std::cmp::min",
          "std::cmp::PartialEq",
          "std::cmp::min_by_key",
          "std::cmp::max",
          "std::format_args!",
          "std::is_mips_feature_detected",
          "std::include",
          "std::is_mips64_feature_detected!",
          "std::u8",
          "std::u8::MAX",
          "std::u8::MIN",
          "std::is_powerpc_feature_detected!",
          "std::where",
          "std::log_syntax!",
          "std::prim_u32",
          "std::u128",
          "std::pin",
          "std::pin::Pin",
          "std::u8",
          "std::prim_fn",
          "std::i64",
          "std::i64::MAX",
          "std::i64::MIN",
          "std::format_args_nl",
          "std::assert!",
          "std::result",
          "std::result::IterMut",
          "std::result::IntoIter",
          "std::result::Iter",
          "std::result::Result",
          "std::continue",
          "std::net::SocketAddrV6",
          "std::net::SocketAddr",
          "std::net",
          "std::net::Ipv4Addr",
          "std::net::udp::UdpSocket",
          "std::net::Incoming",
          "std::net::AddrParseError",
          "std::net::UdpSocket",
          "std::net::TcpListener",
          "std::net::parser::AddrParseError",
          "std::net::Ipv6MulticastScope",
          "std::net::Shutdown",
          "std::net::Ipv6Addr",
          "std::net::tcp::Incoming",
          "std::net::tcp::TcpListener",
          "std::net::tcp::TcpStream",
          "std::net::TcpStream",
          "std::net::ToSocketAddrs",
          "std::net::SocketAddrV4",
          "std::net::ip::Ipv4Addr",
          "std::net::ip::Ipv6MulticastScope",
          "std::net::ip::Ipv6Addr",
          "std::net::ip::IpAddr",
          "std::net::addr::SocketAddrV6",
          "std::net::addr::SocketAddr",
          "std::net::addr::ToSocketAddrs",
          "std::net::addr::SocketAddrV4",
          "std::net::IpAddr",
          "std",
          "std::iter::Extend",
          "std::iter::zip",
          "std::iter::repeat_with",
          "std::iter::Iterator",
          "std::iter::TrustedLen",
          "std::iter::StepBy",
          "std::iter::Chain",
          "std::iter::OnceWith",
          "std::iter",
          "std::iter::once_with",
          "std::iter::FromIterator",
          "std::iter::TrustedStep",
          "std::iter::FromFn",
          "std::iter::IntoIterator",
          "std::iter::Product",
          "std::iter::Cloned",
          "std::iter::Repeat",
          "std::iter::RepeatWith",
          "std::iter::Enumerate",
          "std::iter::from_fn",
          "std::iter::Successors",
          "std::iter::FlatMap",
          "std::iter::Scan",
          "std::iter::Rev",
          "std::iter::Take",
          "std::iter::Copied",
          "std::iter::FusedIterator",
          "std::iter::successors",
          "std::iter::Step",
          "std::iter::repeat",
          "std::iter::FilterMap",
          "std::iter::Once",
          "std::iter::Empty",
          "std::iter::SkipWhile",
          "std::iter::Fuse",
          "std::iter::Skip",
          "std::iter::TakeWhile",
          "std::iter::Flatten",
          "std::iter::Zip",
          "std::iter::empty",
          "std::iter::ExactSizeIterator",
          "std::iter::Peekable",
          "std::iter::MapWhile",
          "std::iter::IntersperseWith",
          "std::iter::Inspect",
          "std::iter::Intersperse",
          "std::iter::once",
          "std::iter::Map",
          "std::iter::Sum",
          "std::iter::Filter",
          "std::iter::Cycle",
          "std::iter::DoubleEndedIterator",
          "std::unimplemented!",
          "std::vec",
          "std::sys_common::wtf8::EncodeWide",
          "std::sys_common::process::CommandEnvs",
          "std::char::REPLACEMENT_CHARACTER",
          "std::char::EscapeDebug",
          "std::char",
          "std::char::from_digit",
          "std::char::UNICODE_VERSION",
          "std::char::EscapeUnicode",
          "std::char::MAX",
          "std::char::CharTryFromError",
          "std::char::decode_utf16",
          "std::char::DecodeUtf16",
          "std::char::DecodeUtf16Error",
          "std::char::ToLowercase",
          "std::char::from_u32",
          "std::char::from_u32_unchecked",
          "std::char::ParseCharError",
          "std::char::ToUppercase",
          "std::char::EscapeDefault",
          "std::alloc::Allocator",
          "std::alloc::System",
          "std::alloc",
          "std::alloc::handle_alloc_error",
          "std::alloc::GlobalAlloc",
          "std::alloc::alloc_zeroed",
          "std::alloc::Layout",
          "std::alloc::dealloc",
          "std::alloc::Global",
          "std::alloc::LayoutErr",
          "std::alloc::realloc",
          "std::alloc::take_alloc_error_hook",
          "std::alloc::alloc",
          "std::alloc::LayoutError",
          "std::alloc::set_alloc_error_hook",
          "std::alloc::AllocError",
          "std::else",
          "std::include_bytes!",
          "std::vec!",
          "std::llvm_asm",
          "std::file",
          "std::assert",
          "std::as",
          "std::prim_i32",
          "std::unimplemented",
          "std::u64",
          "std::prim_isize",
          "std::debug_assert_ne",
          "std::await",
          "std::option_env!",
          "std::hash::Hash",
          "std::hash",
          "std::hash::Hasher",
          "std::hash::Hash!",
          "std::hash::BuildHasherDefault",
          "std::hash::BuildHasher",
          "std::hash::Hash",
          "std::hash::SipHasher",
          "std::type",
          "std::concat!",
          "std::array",
          "std::array::from_mut",
          "std::array::from_ref",
          "std::array::IntoIter",
          "std::array::TryFromSliceError",
          "std::pub",
          "std::super",
          "std::assert_eq",
          "std::log_syntax",
          "std::self",
          "std::SelfTy",
          "std::fmt::Alignment",
          "std::fmt::UpperExp",
          "std::fmt::DebugSet",
          "std::fmt",
          "std::fmt::UpperHex",
          "std::fmt::DebugList",
          "std::fmt::Pointer",
          "std::fmt::DebugStruct",
          "std::fmt::Error",
          "std::fmt::Octal",
          "std::fmt::write",
          "std::fmt::Formatter",
          "std::fmt::LowerExp",
          "std::fmt::Write",
          "std::fmt::DebugTuple",
          "std::fmt::LowerHex",
          "std::fmt::Binary",
          "std::fmt::Debug!",
          "std::fmt::format",
          "std::fmt::Debug",
          "std::fmt::Debug",
          "std::fmt::Display",
          "std::fmt::Result",
          "std::fmt::Arguments",
          "std::fmt::DebugMap",
          "std::prim_i16",
          "std::mut",
          "std::backtrace",
          "std::backtrace::Backtrace",
          "std::backtrace::BacktraceStatus",
          "std::backtrace::BacktraceFrame",
          "std::dbg!",
          "std::slice::Chunks",
          "std::slice::RChunksExactMut",
          "std::slice::GroupByMut",
          "std::slice::GroupBy",
          "std::slice::from_raw_parts_mut",
          "std::slice::SplitN",
          "std::slice::ChunksExact",
          "std::slice",
          "std::slice::ArrayWindows",
          "std::slice::Split",
          "std::slice::Concat",
          "std::slice::RSplitMut",
          "std::slice::from_mut",
          "std::slice::Join",
          "std::slice::SplitMut",
          "std::slice::ChunksExactMut",
          "std::slice::ArrayChunks",
          "std::slice::from_ref",
          "std::slice::IterMut",
          "std::slice::RChunks",
          "std::slice::Windows",
          "std::slice::SplitNMut",
          "std::slice::RChunksMut",
          "std::slice::SliceIndex",
          "std::slice::RSplitN",
          "std::slice::RChunksExact",
          "std::slice::ArrayChunksMut",
          "std::slice::range",
          "std::slice::from_raw_parts",
          "std::slice::RSplitNMut",
          "std::slice::Iter",
          "std::slice::RSplit",
          "std::slice::ChunksMut",
          "std::async",
          "std::include_str",
          "std::concat_idents!",
          "std::i64",
          "std::path::Prefix",
          "std::path::is_separator",
          "std::path",
          "std::path::StripPrefixError",
          "std::path::PrefixComponent",
          "std::path::Display",
          "std::path::Components",
          "std::path::PathBuf",
          "std::path::Path",
          "std::path::Ancestors",
          "std::path::MAIN_SEPARATOR",
          "std::path::Component",
          "std::path::Iter",
          "std::false",
          "std::let",
          "std::stream::Stream",
          "std::stream",
          "std::i8",
          "std::i8::MAX",
          "std::i8::MIN",
          "std::include_bytes",
          "std::usize",
          "std::usize::MAX",
          "std::usize::MIN",
          "std::format",
          "std::primitive",
          "std::thread_local!",
          "std::io::Stdin",
          "std::io::IntoInnerError",
          "std::io::IoSlice",
          "std::io::Chain",
          "std::io",
          "std::io::ErrorKind",
          "std::io::stdin",
          "std::io::LineWriter",
          "std::io::StdoutLock",
          "std::io::Stdout",
          "std::io::util::Sink",
          "std::io::util::Repeat",
          "std::io::util::sink",
          "std::io::util::repeat",
          "std::io::util::Empty",
          "std::io::util::empty",
          "std::io::Sink",
          "std::io::cursor::Cursor",
          "std::io::Bytes",
          "std::io::Lines",
          "std::io::Stderr",
          "std::io::Split",
          "std::io::Repeat",
          "std::io::Read",
          "std::io::StderrLock",
          "std::io::read_to_string",
          "std::io::SeekFrom",
          "std::io::StdinLock",
          "std::io::sink",
          "std::io::Take",
          "std::io::stderr_locked",
          "std::io::stderr",
          "std::io::Error",
          "std::io::stdio::Stdin",
          "std::io::stdio::stdin",
          "std::io::stdio::StdoutLock",
          "std::io::stdio::Stdout",
          "std::io::stdio::Stderr",
          "std::io::stdio::StderrLock",
          "std::io::stdio::StdinLock",
          "std::io::stdio::stderr_locked",
          "std::io::stdio::stderr",
          "std::io::stdio::stdout_locked",
          "std::io::stdio::stdin_locked",
          "std::io::stdio::stdout",
          "std::io::repeat",
          "std::io::Empty",
          "std::io::Write",
          "std::io::stdout_locked",
          "std::io::stdin_locked",
          "std::io::BufRead",
          "std::io::empty",
          "std::io::Seek",
          "std::io::copy::copy",
          "std::io::IoSliceMut",
          "std::io::BufReader",
          "std::io::prelude",
          "std::io::copy",
          "std::io::error::ErrorKind",
          "std::io::error::Error",
          "std::io::error::Result",
          "std::io::buffered::IntoInnerError",
          "std::io::buffered::bufwriter::BufWriter",
          "std::io::buffered::linewriter::LineWriter",
          "std::io::buffered::bufreader::BufReader",
          "std::io::Result",
          "std::io::Cursor",
          "std::io::stdout",
          "std::io::BufWriter",
          "std::io::Initializer",
          "std::is_arm_feature_detected!",
          "std::union",
          "std::is_aarch64_feature_detected",
          "std::stringify!",
          "std::format_args",
          "std::cfg",
          "std::compile_error!",
          "std::prim_f64",
          "std::eprintln",
          "std::println!",
          "std::prim_i128",
          "std::ref",
          "std::unit",
          "std::debug_assert!",
          "std::matches",
          "std::num::NonZeroIsize",
          "std::num::NonZeroI32",
          "std::num::NonZeroU8",
          "std::num::NonZeroU128",
          "std::num::IntErrorKind",
          "std::num::NonZeroI128",
          "std::num::TryFromIntError",
          "std::num",
          "std::num::Wrapping",
          "std::num::NonZeroI64",
          "std::num::NonZeroU64",
          "std::num::NonZeroU32",
          "std::num::NonZeroI8",
          "std::num::ParseIntError",
          "std::num::NonZeroI16",
          "std::num::NonZeroUsize",
          "std::num::FpCategory",
          "std::num::ParseFloatError",
          "std::num::NonZeroU16",
          "std::tuple",
          "std::default::Default!",
          "std::default",
          "std::default::Default",
          "std::default::Default",
          "std::default::default",
          "std::in",
          "std::i8",
          "std::f32::NAN",
          "std::f32::MIN_10_EXP",
          "std::f32",
          "std::f32::MAX",
          "std::f32::MIN",
          "std::f32::EPSILON",
          "std::f32::MAX_10_EXP",
          "std::f32::MIN_EXP",
          "std::f32::RADIX",
          "std::f32::MIN_POSITIVE",
          "std::f32::MAX_EXP",
          "std::f32::MANTISSA_DIGITS",
          "std::f32::INFINITY",
          "std::f32::consts::FRAC_PI_6",
          "std::f32::consts::E",
          "std::f32::consts",
          "std::f32::consts::LOG2_10",
          "std::f32::consts::PI",
          "std::f32::consts::FRAC_PI_2",
          "std::f32::consts::LOG10_2",
          "std::f32::consts::FRAC_PI_3",
          "std::f32::consts::SQRT_2",
          "std::f32::consts::LOG10_E",
          "std::f32::consts::FRAC_1_PI",
          "std::f32::consts::FRAC_2_SQRT_PI",
          "std::f32::consts::FRAC_PI_4",
          "std::f32::consts::LN_10",
          "std::f32::consts::FRAC_1_SQRT_2",
          "std::f32::consts::FRAC_PI_8",
          "std::f32::consts::TAU",
          "std::f32::consts::FRAC_2_PI",
          "std::f32::consts::LN_2",
          "std::f32::consts::LOG2_E",
          "std::f32::DIGITS",
          "std::f32::NEG_INFINITY",
          "std::is_powerpc64_feature_detected",
          "std::env",
          "std::boxed::Box",
          "std::boxed",
          "std::is_mips64_feature_detected",
          "std::todo",
          "std::i32",
          "std::isize",
          "std::option",
          "std::option::IterMut",
          "std::option::IntoIter",
          "std::option::Option",
          "std::option::Iter",
          "std::is_powerpc_feature_detected",
          "std::prim_str",
          "std::while",
          "std::prim_u16",
          "std::line",
          "std::never",
          "std::prim_u128",
          "std::eprint",
          "std::is_x86_feature_detected!",
          "std::include!",
          "std::assert_eq!",
          "std::time::UNIX_EPOCH",
          "std::time",
          "std::time::SystemTimeError",
          "std::time::Duration",
          "std::time::SystemTime",
          "std::time::Instant",
          "std::u32",
          "std::u32::MAX",
          "std::u32::MIN",
          "std::for",
          "std::unreachable",
          "std::prim_array",
          "std::env::var",
          "std::env",
          "std::env::join_paths",
          "std::env::ArgsOs",
          "std::env::var_os",
          "std::env::vars_os",
          "std::env::set_current_dir",
          "std::env::split_paths",
          "std::env::current_exe",
          "std::env::JoinPathsError",
          "std::env::remove_var",
          "std::env::temp_dir",
          "std::env::home_dir",
          "std::env::Args",
          "std::env::vars",
          "std::env::SplitPaths",
          "std::env::args_os",
          "std::env::consts::ARCH",
          "std::env::consts",
          "std::env::consts::DLL_SUFFIX",
          "std::env::consts::FAMILY",
          "std::env::consts::DLL_PREFIX",
          "std::env::consts::OS",
          "std::env::consts::DLL_EXTENSION",
          "std::env::consts::EXE_SUFFIX",
          "std::env::consts::EXE_EXTENSION",
          "std::env::set_var",
          "std::env::current_dir",
          "std::env::VarsOs",
          "std::env::args",
          "std::env::Vars",
          "std::env::VarError",
          "std::prim_tuple",
          "std::prim_ref",
          "std::prim_char",
          "std::write!",
          "std::stringify",
          "std::isize",
          "std::isize::MAX",
          "std::isize::MIN",
          "std::debug_assert_eq",
          "std::cell::BorrowMutError",
          "std::cell",
          "std::cell::BorrowError",
          "std::cell::UnsafeCell",
          "std::cell::Cell",
          "std::cell::RefCell",
          "std::cell::Ref",
          "std::cell::RefMut",
          "std::any",
          "std::any::type_name_of_val",
          "std::any::Any",
          "std::any::TypeId",
          "std::any::type_name",
          "std::column!",
          "std::println",
          "std::u16",
          "std::prim_u64",
          "std::concat",
          "std::debug_assert_eq!",
          "std::is_mips_feature_detected!",
          "std::true",
          "std::break",
          "std::bool",
          "std::vec::Vec",
          "std::vec",
          "std::vec::IntoIter",
          "std::vec::DrainFilter",
          "std::vec::Splice",
          "std::vec::Drain",
          "std::dbg",
          "std::line!",
          "std::clone",
          "std::clone::Clone!",
          "std::clone::Clone",
          "std::clone::Clone",
          "std::extern",
          "std::ffi",
          "std::ffi::OsStr",
          "std::ffi::IntoStringError",
          "std::ffi::VaListImpl",
          "std::ffi::FromBytesWithNulError",
          "std::ffi::OsString",
          "std::ffi::c_str::IntoStringError",
          "std::ffi::c_str::FromBytesWithNulError",
          "std::ffi::c_str::NulError",
          "std::ffi::c_str::CString",
          "std::ffi::c_str::CStr",
          "std::ffi::c_str::FromVecWithNulError",
          "std::ffi::VaList",
          "std::ffi::os_str::OsStr",
          "std::ffi::os_str::OsString",
          "std::ffi::NulError",
          "std::ffi::CString",
          "std::ffi::CStr",
          "std::ffi::FromVecWithNulError",
          "std::ffi::c_void",
          "std::borrow",
          "std::borrow::ToOwned",
          "std::borrow::Cow",
          "std::borrow::Borrow",
          "std::borrow::BorrowMut",
          "std::trace_macros",
          "std::unreachable!",
          "std::env!",
          "std::impl",
          "std::panic::always_abort",
          "std::panic::Location",
          "std::panic::UnwindSafe",
          "std::panic",
          "std::panic::PanicInfo",
          "std::panic::take_hook",
          "std::panic::AssertUnwindSafe",
          "std::panic::resume_unwind",
          "std::panic::panic_any",
          "std::panic::catch_unwind",
          "std::panic::RefUnwindSafe",
          "std::panic::set_hook",
          "std::dyn",
          "std::ptr::addr_of",
          "std::ptr::from_raw_parts_mut",
          "std::ptr::read_volatile",
          "std::ptr::read",
          "std::ptr::DynMetadata",
          "std::ptr",
          "std::ptr::drop_in_place",
          "std::ptr::eq",
          "std::ptr::write_unaligned",
          "std::ptr::null_mut",
          "std::ptr::null",
          "std::ptr::hash",
          "std::ptr::swap",
          "std::ptr::slice_from_raw_parts_mut",
          "std::ptr::addr_of_mut",
          "std::ptr::write_volatile",
          "std::ptr::metadata",
          "std::ptr::write",
          "std::ptr::copy_nonoverlapping",
          "std::ptr::replace",
          "std::ptr::write_bytes",
          "std::ptr::Pointee",
          "std::ptr::slice_from_raw_parts",
          "std::ptr::swap_nonoverlapping",
          "std::ptr::copy",
          "std::ptr::addr_of!",
          "std::ptr::from_raw_parts",
          "std::ptr::NonNull",
          "std::ptr::read_unaligned",
          "std::ptr::addr_of_mut!",
          "std::write",
          "std::format_args_nl!",
          "std::const",
          "std::task",
          "std::task::Wake",
          "std::task::RawWakerVTable",
          "std::task::Waker",
          "std::task::ready",
          "std::task::Context",
          "std::task::ready!",
          "std::task::RawWaker",
          "std::task::Poll",
          "std::writeln!",
          "std::lazy::SyncLazy",
          "std::lazy",
          "std::lazy::SyncOnceCell",
          "std::lazy::Lazy",
          "std::lazy::OnceCell",
          "std::writeln",
          "std::i32",
          "std::i32::MAX",
          "std::i32::MIN",
          "std::is_powerpc64_feature_detected!",
          "std::include_str!",
          "std::enum",
          "std::pointer",
          "std::prim_i8",
          "std::prim_unit",
          "std::cfg!",
          "std::debug_assert",
          "std::file!",
          "std::prim_i64",
          "std::try!",
          "std::mod",
          "std::option_env",
          "std::ops::Deref",
          "std::ops::Sub",
          "std::ops::GeneratorState",
          "std::ops::FromResidual",
          "std::ops",
          "std::ops::MulAssign",
          "std::ops::CoerceUnsized",
          "std::ops::IndexMut",
          "std::ops::RangeFull",
          "std::ops::RangeToInclusive",
          "std::ops::BitOr",
          "std::ops::Index",
          "std::ops::Not",
          "std::ops::Bound",
          "std::ops::Try",
          "std::ops::Drop",
          "std::ops::DivAssign",
          "std::ops::BitXorAssign",
          "std::ops::RangeFrom",
          "std::ops::FnOnce",
          "std::ops::Mul",
          "std::ops::Shr",
          "std::ops::Fn",
          "std::ops::AddAssign",
          "std::ops::RangeTo",
          "std::ops::Range",
          "std::ops::BitXor",
          "std::ops::DispatchFromDyn",
          "std::ops::RemAssign",
          "std::ops::RangeBounds",
          "std::ops::BitAndAssign",
          "std::ops::Neg",
          "std::ops::DerefMut",
          "std::ops::RangeInclusive",
          "std::ops::ShrAssign",
          "std::ops::ShlAssign",
          "std::ops::Add",
          "std::ops::Div",
          "std::ops::FnMut",
          "std::ops::SubAssign",
          "std::ops::Generator",
          "std::ops::Rem",
          "std::ops::BitOrAssign",
          "std::ops::ControlFlow",
          "std::ops::Shl",
          "std::ops::BitAnd",
          "std::compile_error",
          "std::os",
          "std::os::unix::net::Messages",
          "std::os::unix::net::SocketAddr",
          "std::os::unix::net",
          "std::os::unix::net::ScmCredentials",
          "std::os::unix::net::Incoming",
          "std::os::unix::net::UnixStream",
          "std::os::unix::net::UnixDatagram",
          "std::os::unix::net::ScmRights",
          "std::os::unix::net::UCred",
          "std::os::unix::net::SocketAncillary",
          "std::os::unix::net::AncillaryError",
          "std::os::unix::net::AncillaryData",
          "std::os::unix::net::UnixListener",
          "std::os::unix::net::SocketCred",
          "std::os::unix",
          "std::os::unix::io",
          "std::os::unix::io::RawFd",
          "std::os::unix::io::IntoRawFd",
          "std::os::unix::io::AsRawFd",
          "std::os::unix::io::FromRawFd",
          "std::os::unix::ffi::OsStringExt",
          "std::os::unix::ffi",
          "std::os::unix::ffi::OsStrExt",
          "std::os::unix::prelude",
          "std::os::unix::fs::DirBuilderExt",
          "std::os::unix::fs::FileTypeExt",
          "std::os::unix::fs",
          "std::os::unix::fs::symlink",
          "std::os::unix::fs::DirEntryExt",
          "std::os::unix::fs::FileExt",
          "std::os::unix::fs::DirEntryExt2",
          "std::os::unix::fs::OpenOptionsExt",
          "std::os::unix::fs::PermissionsExt",
          "std::os::unix::fs::chroot",
          "std::os::unix::fs::MetadataExt",
          "std::os::unix::thread",
          "std::os::unix::thread::JoinHandleExt",
          "std::os::unix::thread::RawPthread",
          "std::os::unix::raw::off_t",
          "std::os::unix::raw",
          "std::os::unix::raw::gid_t",
          "std::os::unix::raw::dev_t",
          "std::os::unix::raw::mode_t",
          "std::os::unix::raw::nlink_t",
          "std::os::unix::raw::uid_t",
          "std::os::unix::raw::time_t",
          "std::os::unix::raw::pid_t",
          "std::os::unix::raw::ino_t",
          "std::os::unix::raw::blksize_t",
          "std::os::unix::raw::pthread_t",
          "std::os::unix::raw::blkcnt_t",
          "std::os::unix::ucred",
          "std::os::unix::ucred::UCred",
          "std::os::unix::ucred::impl_mac",
          "std::os::unix::ucred::impl_mac::peer_cred",
          "std::os::unix::ucred::peer_cred",
          "std::os::unix::process",
          "std::os::unix::process::parent_id",
          "std::os::unix::process::ExitStatusExt",
          "std::os::unix::process::CommandExt",
          "std::os::linux",
          "std::os::linux::fs",
          "std::os::linux::fs::MetadataExt",
          "std::os::linux::raw::off_t",
          "std::os::linux::raw",
          "std::os::linux::raw::stat",
          "std::os::linux::raw::dev_t",
          "std::os::linux::raw::mode_t",
          "std::os::linux::raw::nlink_t",
          "std::os::linux::raw::time_t",
          "std::os::linux::raw::ino_t",
          "std::os::linux::raw::blksize_t",
          "std::os::linux::raw::pthread_t",
          "std::os::linux::raw::blkcnt_t",
          "std::os::doc::unix::net::listener::Incoming",
          "std::os::doc::unix::net::listener::UnixListener",
          "std::os::doc::unix::net",
          "std::os::doc::unix::net::stream::UnixStream",
          "std::os::doc::unix::net::ancillary::Messages",
          "std::os::doc::unix::net::ancillary::ScmCredentials",
          "std::os::doc::unix::net::ancillary::ScmRights",
          "std::os::doc::unix::net::ancillary::SocketAncillary",
          "std::os::doc::unix::net::ancillary::AncillaryError",
          "std::os::doc::unix::net::ancillary::AncillaryData",
          "std::os::doc::unix::net::ancillary::SocketCred",
          "std::os::doc::unix::net::addr::SocketAddr",
          "std::os::doc::unix::net::datagram::UnixDatagram",
          "std::os::doc::unix",
          "std::os::doc::unix::io",
          "std::os::doc::unix::io::RawFd",
          "std::os::doc::unix::io::IntoRawFd",
          "std::os::doc::unix::io::AsRawFd",
          "std::os::doc::unix::io::FromRawFd",
          "std::os::doc::unix::ffi",
          "std::os::doc::unix::ffi::os_str::OsStringExt",
          "std::os::doc::unix::ffi::os_str::OsStrExt",
          "std::os::doc::unix::prelude",
          "std::os::doc::unix::fs::DirBuilderExt",
          "std::os::doc::unix::fs::FileTypeExt",
          "std::os::doc::unix::fs",
          "std::os::doc::unix::fs::symlink",
          "std::os::doc::unix::fs::DirEntryExt",
          "std::os::doc::unix::fs::FileExt",
          "std::os::doc::unix::fs::DirEntryExt2",
          "std::os::doc::unix::fs::OpenOptionsExt",
          "std::os::doc::unix::fs::PermissionsExt",
          "std::os::doc::unix::fs::chroot",
          "std::os::doc::unix::fs::MetadataExt",
          "std::os::doc::unix::thread",
          "std::os::doc::unix::thread::JoinHandleExt",
          "std::os::doc::unix::thread::RawPthread",
          "std::os::doc::unix::raw",
          "std::os::doc::unix::raw::gid_t",
          "std::os::doc::unix::raw::uid_t",
          "std::os::doc::unix::raw::pid_t",
          "std::os::doc::unix::ucred",
          "std::os::doc::unix::ucred::UCred",
          "std::os::doc::unix::ucred::impl_mac",
          "std::os::doc::unix::ucred::impl_mac::peer_cred",
          "std::os::doc::unix::process",
          "std::os::doc::unix::process::parent_id",
          "std::os::doc::unix::process::ExitStatusExt",
          "std::os::doc::unix::process::CommandExt",
          "std::os::doc::linux",
          "std::os::doc::linux::fs",
          "std::os::doc::linux::fs::MetadataExt",
          "std::os::doc::linux::raw",
          "std::os::doc::linux::raw::dev_t",
          "std::os::doc::linux::raw::mode_t",
          "std::os::doc::linux::raw::arch::off_t",
          "std::os::doc::linux::raw::arch::stat",
          "std::os::doc::linux::raw::arch::nlink_t",
          "std::os::doc::linux::raw::arch::time_t",
          "std::os::doc::linux::raw::arch::ino_t",
          "std::os::doc::linux::raw::arch::blksize_t",
          "std::os::doc::linux::raw::arch::blkcnt_t",
          "std::os::doc::linux::raw::pthread_t",
          "std::os::doc::wasi",
          "std::os::doc::wasi::io",
          "std::os::doc::wasi::io::RawFd",
          "std::os::doc::wasi::io::IntoRawFd",
          "std::os::doc::wasi::io::AsRawFd",
          "std::os::doc::wasi::io::FromRawFd",
          "std::os::doc::wasi::ffi",
          "std::os::doc::wasi::ffi::os_str::OsStringExt",
          "std::os::doc::wasi::ffi::os_str::OsStrExt",
          "std::os::doc::wasi::prelude",
          "std::os::doc::wasi::fs::FileTypeExt",
          "std::os::doc::wasi::fs",
          "std::os::doc::wasi::fs::link",
          "std::os::doc::wasi::fs::symlink",
          "std::os::doc::wasi::fs::DirEntryExt",
          "std::os::doc::wasi::fs::FileExt",
          "std::os::doc::wasi::fs::symlink_path",
          "std::os::doc::wasi::fs::OpenOptionsExt",
          "std::os::doc::wasi::fs::MetadataExt",
          "std::os::doc::wasi::fs::rename",
          "std::os::doc::windows",
          "std::os::doc::windows::io::FromRawHandle",
          "std::os::doc::windows::io::AsRawSocket",
          "std::os::doc::windows::io::RawSocket",
          "std::os::doc::windows::io",
          "std::os::doc::windows::io::IntoRawSocket",
          "std::os::doc::windows::io::IntoRawHandle",
          "std::os::doc::windows::io::FromRawSocket",
          "std::os::doc::windows::io::AsRawHandle",
          "std::os::doc::windows::io::RawHandle",
          "std::os::doc::windows::ffi::OsStringExt",
          "std::os::doc::windows::ffi",
          "std::os::doc::windows::ffi::OsStrExt",
          "std::os::doc::windows::prelude",
          "std::os::doc::windows::fs::FileTypeExt",
          "std::os::doc::windows::fs",
          "std::os::doc::windows::fs::symlink_file",
          "std::os::doc::windows::fs::FileExt",
          "std::os::doc::windows::fs::OpenOptionsExt",
          "std::os::doc::windows::fs::MetadataExt",
          "std::os::doc::windows::fs::symlink_dir",
          "std::os::doc::windows::thread",
          "std::os::doc::windows::raw",
          "std::os::doc::windows::raw::SOCKET",
          "std::os::doc::windows::raw::HANDLE",
          "std::os::doc::windows::process",
          "std::os::doc::windows::process::ExitStatusExt",
          "std::os::doc::windows::process::CommandExt",
          "std::os::wasi",
          "std::os::wasi::io",
          "std::os::wasi::io::RawFd",
          "std::os::wasi::io::IntoRawFd",
          "std::os::wasi::io::AsRawFd",
          "std::os::wasi::io::FromRawFd",
          "std::os::wasi::ffi::OsStringExt",
          "std::os::wasi::ffi",
          "std::os::wasi::ffi::OsStrExt",
          "std::os::wasi::prelude",
          "std::os::wasi::fs::FileTypeExt",
          "std::os::wasi::fs",
          "std::os::wasi::fs::link",
          "std::os::wasi::fs::symlink",
          "std::os::wasi::fs::DirEntryExt",
          "std::os::wasi::fs::FileExt",
          "std::os::wasi::fs::symlink_path",
          "std::os::wasi::fs::OpenOptionsExt",
          "std::os::wasi::fs::MetadataExt",
          "std::os::wasi::fs::rename",
          "std::os::windows",
          "std::os::windows::io::FromRawHandle",
          "std::os::windows::io::AsRawSocket",
          "std::os::windows::io::RawSocket",
          "std::os::windows::io",
          "std::os::windows::io::IntoRawSocket",
          "std::os::windows::io::IntoRawHandle",
          "std::os::windows::io::FromRawSocket",
          "std::os::windows::io::AsRawHandle",
          "std::os::windows::io::RawHandle",
          "std::os::windows::ffi::OsStringExt",
          "std::os::windows::ffi",
          "std::os::windows::ffi::EncodeWide",
          "std::os::windows::ffi::OsStrExt",
          "std::os::windows::prelude",
          "std::os::windows::fs::FileTypeExt",
          "std::os::windows::fs",
          "std::os::windows::fs::symlink_file",
          "std::os::windows::fs::FileExt",
          "std::os::windows::fs::OpenOptionsExt",
          "std::os::windows::fs::MetadataExt",
          "std::os::windows::fs::symlink_dir",
          "std::os::windows::thread",
          "std::os::windows::raw",
          "std::os::windows::raw::SOCKET",
          "std::os::windows::raw::HANDLE",
          "std::os::windows::process",
          "std::os::windows::process::ExitStatusExt",
          "std::os::windows::process::CommandExt",
          "std::os::raw::c_int",
          "std::os::raw::NonZero_c_int",
          "std::os::raw::c_double",
          "std::os::raw::c_char",
          "std::os::raw::c_short",
          "std::os::raw",
          "std::os::raw::NonZero_c_uchar",
          "std::os::raw::c_uint",
          "std::os::raw::c_schar",
          "std::os::raw::c_float",
          "std::os::raw::NonZero_c_schar",
          "std::os::raw::NonZero_c_char",
          "std::os::raw::NonZero_c_ulonglong",
          "std::os::raw::c_uchar",
          "std::os::raw::NonZero_c_longlong",
          "std::os::raw::NonZero_c_short",
          "std::os::raw::NonZero_c_uint",
          "std::os::raw::c_longlong",
          "std::os::raw::c_ushort",
          "std::os::raw::NonZero_c_ushort",
          "std::os::raw::NonZero_c_long",
          "std::os::raw::c_ulong",
          "std::os::raw::c_ulonglong",
          "std::os::raw::c_long",
          "std::os::raw::NonZero_c_ulong",
          "std::slice",
          "std::intrinsics::ptr_guaranteed_eq",
          "std::intrinsics::wrapping_sub",
          "std::intrinsics::raw_eq",
          "std::intrinsics::atomic_max_relaxed",
          "std::intrinsics::nontemporal_store",
          "std::intrinsics::atomic_cxchg",
          "std::intrinsics::atomic_min_relaxed",
          "std::intrinsics::atomic_xchg_relaxed",
          "std::intrinsics::nearbyintf64",
          "std::intrinsics::atomic_cxchgweak_rel",
          "std::intrinsics::fmaf64",
          "std::intrinsics::type_id",
          "std::intrinsics::discriminant_value",
          "std::intrinsics::atomic_xchg_rel",
          "std::intrinsics::atomic_xadd_relaxed",
          "std::intrinsics::abort",
          "std::intrinsics::float_to_int_unchecked",
          "std::intrinsics::atomic_load_acq",
          "std::intrinsics::powf32",
          "std::intrinsics::saturating_add",
          "std::intrinsics::atomic_cxchg_relaxed",
          "std::intrinsics::atomic_cxchgweak_acqrel_failrelaxed",
          "std::intrinsics::atomic_and_relaxed",
          "std::intrinsics::fmul_fast",
          "std::intrinsics::expf32",
          "std::intrinsics::minnumf64",
          "std::intrinsics::atomic_cxchgweak_failacq",
          "std::intrinsics::exp2f64",
          "std::intrinsics::size_of_val",
          "std::intrinsics::unaligned_volatile_load",
          "std::intrinsics::atomic_and_rel",
          "std::intrinsics::fabsf32",
          "std::intrinsics::atomic_nand",
          "std::intrinsics::exp2f32",
          "std::intrinsics::atomic_or_relaxed",
          "std::intrinsics::fabsf64",
          "std::intrinsics",
          "std::intrinsics::cttz_nonzero",
          "std::intrinsics::minnumf32",
          "std::intrinsics::expf64",
          "std::intrinsics::atomic_xor_acqrel",
          "std::intrinsics::atomic_cxchg_acq",
          "std::intrinsics::prefetch_read_instruction",
          "std::intrinsics::atomic_fence",
          "std::intrinsics::atomic_fence_acqrel",
          "std::intrinsics::atomic_or_acq",
          "std::intrinsics::unchecked_shr",
          "std::intrinsics::atomic_cxchg_failrelaxed",
          "std::intrinsics::unchecked_mul",
          "std::intrinsics::powf64",
          "std::intrinsics::assert_inhabited",
          "std::intrinsics::unaligned_volatile_store",
          "std::intrinsics::atomic_cxchgweak_acqrel",
          "std::intrinsics::atomic_cxchg_acq_failrelaxed",
          "std::intrinsics::transmute",
          "std::intrinsics::atomic_xadd_acqrel",
          "std::intrinsics::nearbyintf32",
          "std::intrinsics::fmaf32",
          "std::intrinsics::bswap",
          "std::intrinsics::volatile_store",
          "std::intrinsics::needs_drop",
          "std::intrinsics::drop_in_place",
          "std::intrinsics::atomic_singlethreadfence_acq",
          "std::intrinsics::prefetch_write_instruction",
          "std::intrinsics::volatile_copy_memory",
          "std::intrinsics::powif64",
          "std::intrinsics::assert_zero_valid",
          "std::intrinsics::atomic_or_rel",
          "std::intrinsics::unchecked_div",
          "std::intrinsics::prefetch_read_data",
          "std::intrinsics::atomic_cxchg_rel",
          "std::intrinsics::atomic_load_unordered",
          "std::intrinsics::volatile_set_memory",
          "std::intrinsics::pref_align_of",
          "std::intrinsics::unchecked_rem",
          "std::intrinsics::sqrtf32",
          "std::intrinsics::atomic_min",
          "std::intrinsics::log10f64",
          "std::intrinsics::atomic_singlethreadfence_rel",
          "std::intrinsics::atomic_cxchgweak_failrelaxed",
          "std::intrinsics::truncf32",
          "std::intrinsics::sinf32",
          "std::intrinsics::logf32",
          "std::intrinsics::add_with_overflow",
          "std::intrinsics::atomic_xor",
          "std::intrinsics::rintf64",
          "std::intrinsics::unchecked_shl",
          "std::intrinsics::roundf64",
          "std::intrinsics::atomic_cxchg_failacq",
          "std::intrinsics::atomic_umax_acqrel",
          "std::intrinsics::roundf32",
          "std::intrinsics::atomic_cxchg_acqrel_failrelaxed",
          "std::intrinsics::variant_count",
          "std::intrinsics::atomic_and",
          "std::intrinsics::size_of",
          "std::intrinsics::arith_offset",
          "std::intrinsics::bitreverse",
          "std::intrinsics::atomic_cxchgweak_acq",
          "std::intrinsics::rintf32",
          "std::intrinsics::atomic_cxchgweak",
          "std::intrinsics::truncf64",
          "std::intrinsics::atomic_max",
          "std::intrinsics::sinf64",
          "std::intrinsics::logf64",
          "std::intrinsics::atomic_singlethreadfence",
          "std::intrinsics::atomic_min_acqrel",
          "std::intrinsics::sqrtf64",
          "std::intrinsics::atomic_singlethreadfence_acqrel",
          "std::intrinsics::log10f32",
          "std::intrinsics::atomic_cxchgweak_relaxed",
          "std::intrinsics::exact_div",
          "std::intrinsics::min_align_of",
          "std::intrinsics::atomic_or_acqrel",
          "std::intrinsics::atomic_xsub",
          "std::intrinsics::atomic_and_acq",
          "std::intrinsics::assume",
          "std::intrinsics::fsub_fast",
          "std::intrinsics::atomic_store_rel",
          "std::intrinsics::rustc_peek",
          "std::intrinsics::unchecked_add",
          "std::intrinsics::powif32",
          "std::intrinsics::atomic_xchg_acq",
          "std::intrinsics::ctlz_nonzero",
          "std::intrinsics::volatile_load",
          "std::intrinsics::ctpop",
          "std::intrinsics::caller_location",
          "std::intrinsics::log2f64",
          "std::intrinsics::try",
          "std::intrinsics::wrapping_mul",
          "std::intrinsics::atomic_store",
          "std::intrinsics::offset",
          "std::intrinsics::const_allocate",
          "std::intrinsics::atomic_umax_acq",
          "std::intrinsics::atomic_xchg",
          "std::intrinsics::rotate_right",
          "std::intrinsics::floorf32",
          "std::intrinsics::atomic_umin_rel",
          "std::intrinsics::atomic_umin",
          "std::intrinsics::fadd_fast",
          "std::intrinsics::atomic_fence_acq",
          "std::intrinsics::maxnumf64",
          "std::intrinsics::ptr_offset_from",
          "std::intrinsics::maxnumf32",
          "std::intrinsics::frem_fast",
          "std::intrinsics::atomic_umax",
          "std::intrinsics::forget",
          "std::intrinsics::breakpoint",
          "std::intrinsics::unchecked_sub",
          "std::intrinsics::atomic_xsub_acq",
          "std::intrinsics::atomic_or",
          "std::intrinsics::atomic_xadd",
          "std::intrinsics::atomic_umin_relaxed",
          "std::intrinsics::atomic_and_acqrel",
          "std::intrinsics::atomic_umax_relaxed",
          "std::intrinsics::atomic_store_relaxed",
          "std::intrinsics::copy_nonoverlapping",
          "std::intrinsics::floorf64",
          "std::intrinsics::atomic_xor_rel",
          "std::intrinsics::unlikely",
          "std::intrinsics::atomic_nand_acq",
          "std::intrinsics::write_bytes",
          "std::intrinsics::atomic_load_relaxed",
          "std::intrinsics::atomic_min_acq",
          "std::intrinsics::log2f32",
          "std::intrinsics::atomic_max_rel",
          "std::intrinsics::atomic_xadd_rel",
          "std::intrinsics::cttz",
          "std::intrinsics::ptr_guaranteed_ne",
          "std::intrinsics::atomic_load",
          "std::intrinsics::atomic_xor_relaxed",
          "std::intrinsics::cosf64",
          "std::intrinsics::atomic_xchg_acqrel",
          "std::intrinsics::atomic_nand_acqrel",
          "std::intrinsics::atomic_nand_relaxed",
          "std::intrinsics::atomic_xsub_rel",
          "std::intrinsics::atomic_cxchg_acqrel",
          "std::intrinsics::saturating_sub",
          "std::intrinsics::unreachable",
          "std::intrinsics::copysignf64",
          "std::intrinsics::atomic_max_acq",
          "std::intrinsics::atomic_xadd_acq",
          "std::intrinsics::atomic_min_rel",
          "std::intrinsics::copy",
          "std::intrinsics::ceilf32",
          "std::intrinsics::wrapping_add",
          "std::intrinsics::atomic_nand_rel",
          "std::intrinsics::atomic_xor_acq",
          "std::intrinsics::likely",
          "std::intrinsics::fdiv_fast",
          "std::intrinsics::atomic_umin_acqrel",
          "std::intrinsics::ceilf64",
          "std::intrinsics::assert_uninit_valid",
          "std::intrinsics::atomic_max_acqrel",
          "std::intrinsics::atomic_cxchgweak_acq_failrelaxed",
          "std::intrinsics::prefetch_write_data",
          "std::intrinsics::volatile_copy_nonoverlapping_memory",
          "std::intrinsics::copysignf32",
          "std::intrinsics::atomic_store_unordered",
          "std::intrinsics::atomic_xsub_relaxed",
          "std::intrinsics::atomic_fence_rel",
          "std::intrinsics::ctlz",
          "std::intrinsics::type_name",
          "std::intrinsics::atomic_umin_acq",
          "std::intrinsics::cosf32",
          "std::intrinsics::min_align_of_val",
          "std::intrinsics::sub_with_overflow",
          "std::intrinsics::atomic_xsub_acqrel",
          "std::intrinsics::mul_with_overflow",
          "std::intrinsics::rotate_left",
          "std::intrinsics::atomic_umax_rel",
          "std::f32",
          "std::crate",
          "std::string",
          "std::string::FromUtf16Error",
          "std::string::ToString",
          "std::string::String",
          "std::string::FromUtf8Error",
          "std::string::ParseError",
          "std::string::Drain",
          "std::concat_idents",
          "std::str",
          "std::i128",
          "std::i128::MAX",
          "std::i128::MIN",
          "std::eprintln!",
          "std::move",
          "std::reference",
          "std::struct",
          "std::trace_macros!",
          "std::sync::RwLock",
          "std::sync::TryLockResult",
          "std::sync::MutexGuard",
          "std::sync",
          "std::sync::LockResult",
          "std::sync::ONCE_INIT",
          "std::sync::once::ONCE_INIT",
          "std::sync::once::Once",
          "std::sync::once::OnceState",
          "std::sync::Weak",
          "std::sync::Arc",
          "std::sync::rwlock::RwLock",
          "std::sync::rwlock::RwLockReadGuard",
          "std::sync::rwlock::RwLockWriteGuard",
          "std::sync::RwLockReadGuard",
          "std::sync::Mutex",
          "std::sync::TryLockError",
          "std::sync::BarrierWaitResult",
          "std::sync::RwLockWriteGuard",
          "std::sync::atomic::AtomicI16",
          "std::sync::atomic::ATOMIC_I128_INIT",
          "std::sync::atomic::ATOMIC_BOOL_INIT",
          "std::sync::atomic::compiler_fence",
          "std::sync::atomic::ATOMIC_U16_INIT",
          "std::sync::atomic",
          "std::sync::atomic::AtomicI128",
          "std::sync::atomic::ATOMIC_U8_INIT",
          "std::sync::atomic::AtomicU128",
          "std::sync::atomic::fence",
          "std::sync::atomic::AtomicUsize",
          "std::sync::atomic::AtomicU16",
          "std::sync::atomic::ATOMIC_I16_INIT",
          "std::sync::atomic::ATOMIC_I8_INIT",
          "std::sync::atomic::AtomicI32",
          "std::sync::atomic::AtomicPtr",
          "std::sync::atomic::ATOMIC_I32_INIT",
          "std::sync::atomic::AtomicU8",
          "std::sync::atomic::ATOMIC_I64_INIT",
          "std::sync::atomic::ATOMIC_ISIZE_INIT",
          "std::sync::atomic::spin_loop_hint",
          "std::sync::atomic::Ordering",
          "std::sync::atomic::AtomicBool",
          "std::sync::atomic::AtomicI64",
          "std::sync::atomic::ATOMIC_USIZE_INIT",
          "std::sync::atomic::AtomicIsize",
          "std::sync::atomic::ATOMIC_U128_INIT",
          "std::sync::atomic::AtomicU64",
          "std::sync::atomic::AtomicI8",
          "std::sync::atomic::AtomicU32",
          "std::sync::atomic::ATOMIC_U64_INIT",
          "std::sync::atomic::ATOMIC_U32_INIT",
          "std::sync::poison::TryLockResult",
          "std::sync::poison::LockResult",
          "std::sync::poison::TryLockError",
          "std::sync::poison::PoisonError",
          "std::sync::condvar::Condvar",
          "std::sync::condvar::WaitTimeoutResult",
          "std::sync::barrier::BarrierWaitResult",
          "std::sync::barrier::Barrier",
          "std::sync::Barrier",
          "std::sync::Once",
          "std::sync::PoisonError",
          "std::sync::Condvar",
          "std::sync::mutex::MutexGuard",
          "std::sync::mutex::Mutex",
          "std::sync::WaitTimeoutResult",
          "std::sync::mpsc",
          "std::sync::mpsc::sync_channel",
          "std::sync::mpsc::channel",
          "std::sync::mpsc::IntoIter",
          "std::sync::mpsc::Receiver",
          "std::sync::mpsc::Sender",
          "std::sync::mpsc::SendError",
          "std::sync::mpsc::TrySendError",
          "std::sync::mpsc::RecvTimeoutError",
          "std::sync::mpsc::TryRecvError",
          "std::sync::mpsc::RecvError",
          "std::sync::mpsc::SyncSender",
          "std::sync::mpsc::Iter",
          "std::sync::mpsc::TryIter",
          "std::sync::OnceState",
          "std::prelude::v1",
          "std::prelude",
          "std::prelude::rust_2015",
          "std::prelude::rust_2021",
          "std::prelude::rust_2018",
          "std::panic",
          "std::marker::StructuralEq",
          "std::marker",
          "std::marker::Copy",
          "std::marker::DiscriminantKind",
          "std::marker::Unsize",
          "std::marker::StructuralPartialEq",
          "std::marker::Copy",
          "std::marker::Unpin",
          "std::marker::PhantomData",
          "std::marker::Send",
          "std::marker::Sized",
          "std::marker::Copy!",
          "std::marker::Sync",
          "std::marker::PhantomPinned",
          "std::module_path",
          "std::unsafe",
          "std::is_arm_feature_detected",
          "std::u128",
          "std::u128::MAX",
          "std::u128::MIN",
          "std::i16",
          "std::i16::MAX",
          "std::i16::MIN",
          "std::column",
          "std::fn",
          "std::collections::BinaryHeap",
          "std::collections::btree_map::Values",
          "std::collections::btree_map",
          "std::collections::btree_map::RangeMut",
          "std::collections::btree_map::VacantEntry",
          "std::collections::btree_map::Keys",
          "std::collections::btree_map::Entry",
          "std::collections::btree_map::IterMut",
          "std::collections::btree_map::IntoIter",
          "std::collections::btree_map::BTreeMap",
          "std::collections::btree_map::DrainFilter",
          "std::collections::btree_map::IntoKeys",
          "std::collections::btree_map::OccupiedError",
          "std::collections::btree_map::OccupiedEntry",
          "std::collections::btree_map::Range",
          "std::collections::btree_map::IntoValues",
          "std::collections::btree_map::ValuesMut",
          "std::collections::btree_map::Iter",
          "std::collections::hash_map::RawOccupiedEntryMut",
          "std::collections::hash_map::Values",
          "std::collections::hash_map::RawEntryMut",
          "std::collections::hash_map",
          "std::collections::hash_map::VacantEntry",
          "std::collections::hash_map::Keys",
          "std::collections::hash_map::Entry",
          "std::collections::hash_map::IterMut",
          "std::collections::hash_map::IntoIter",
          "std::collections::hash_map::RawEntryBuilderMut",
          "std::collections::hash_map::RawVacantEntryMut",
          "std::collections::hash_map::DrainFilter",
          "std::collections::hash_map::DefaultHasher",
          "std::collections::hash_map::IntoKeys",
          "std::collections::hash_map::OccupiedError",
          "std::collections::hash_map::RawEntryBuilder",
          "std::collections::hash_map::OccupiedEntry",
          "std::collections::hash_map::Drain",
          "std::collections::hash_map::IntoValues",
          "std::collections::hash_map::HashMap",
          "std::collections::hash_map::ValuesMut",
          "std::collections::hash_map::Iter",
          "std::collections::hash_map::RandomState",
          "std::collections",
          "std::collections::HashSet",
          "std::collections::hash::map::RawOccupiedEntryMut",
          "std::collections::hash::map::Values",
          "std::collections::hash::map::RawEntryMut",
          "std::collections::hash::map::VacantEntry",
          "std::collections::hash::map::Keys",
          "std::collections::hash::map::Entry",
          "std::collections::hash::map::IterMut",
          "std::collections::hash::map::IntoIter",
          "std::collections::hash::map::RawEntryBuilderMut",
          "std::collections::hash::map::RawVacantEntryMut",
          "std::collections::hash::map::DrainFilter",
          "std::collections::hash::map::DefaultHasher",
          "std::collections::hash::map::IntoKeys",
          "std::collections::hash::map::OccupiedError",
          "std::collections::hash::map::RawEntryBuilder",
          "std::collections::hash::map::OccupiedEntry",
          "std::collections::hash::map::Drain",
          "std::collections::hash::map::IntoValues",
          "std::collections::hash::map::HashMap",
          "std::collections::hash::map::ValuesMut",
          "std::collections::hash::map::Iter",
          "std::collections::hash::map::RandomState",
          "std::collections::hash::set::HashSet",
          "std::collections::hash::set::Union",
          "std::collections::hash::set::IntoIter",
          "std::collections::hash::set::Difference",
          "std::collections::hash::set::DrainFilter",
          "std::collections::hash::set::Drain",
          "std::collections::hash::set::SymmetricDifference",
          "std::collections::hash::set::Iter",
          "std::collections::hash::set::Intersection",
          "std::collections::btree_set",
          "std::collections::btree_set::Union",
          "std::collections::btree_set::BTreeSet",
          "std::collections::btree_set::IntoIter",
          "std::collections::btree_set::Difference",
          "std::collections::btree_set::DrainFilter",
          "std::collections::btree_set::Range",
          "std::collections::btree_set::SymmetricDifference",
          "std::collections::btree_set::Iter",
          "std::collections::btree_set::Intersection",
          "std::collections::hash_set",
          "std::collections::hash_set::HashSet",
          "std::collections::hash_set::Union",
          "std::collections::hash_set::IntoIter",
          "std::collections::hash_set::Difference",
          "std::collections::hash_set::DrainFilter",
          "std::collections::hash_set::Drain",
          "std::collections::hash_set::SymmetricDifference",
          "std::collections::hash_set::Iter",
          "std::collections::hash_set::Intersection",
          "std::collections::vec_deque",
          "std::collections::vec_deque::IterMut",
          "std::collections::vec_deque::IntoIter",
          "std::collections::vec_deque::VecDeque",
          "std::collections::vec_deque::Drain",
          "std::collections::vec_deque::Iter",
          "std::collections::linked_list",
          "std::collections::linked_list::CursorMut",
          "std::collections::linked_list::IterMut",
          "std::collections::linked_list::IntoIter",
          "std::collections::linked_list::DrainFilter",
          "std::collections::linked_list::LinkedList",
          "std::collections::linked_list::Iter",
          "std::collections::linked_list::Cursor",
          "std::collections::BTreeSet",
          "std::collections::VecDeque",
          "std::collections::BTreeMap",
          "std::collections::TryReserveError",
          "std::collections::binary_heap::BinaryHeap",
          "std::collections::binary_heap",
          "std::collections::binary_heap::PeekMut",
          "std::collections::binary_heap::IntoIter",
          "std::collections::binary_heap::DrainSorted",
          "std::collections::binary_heap::IntoIterSorted",
          "std::collections::binary_heap::Drain",
          "std::collections::binary_heap::Iter",
          "std::collections::LinkedList",
          "std::collections::HashMap",
          "std::fs::Permissions",
          "std::fs::remove_file",
          "std::fs::read",
          "std::fs",
          "std::fs::read_link",
          "std::fs::Metadata",
          "std::fs::OpenOptions",
          "std::fs::hard_link",
          "std::fs::create_dir_all",
          "std::fs::read_to_string",
          "std::fs::symlink_metadata",
          "std::fs::canonicalize",
          "std::fs::set_permissions",
          "std::fs::DirBuilder",
          "std::fs::try_exists",
          "std::fs::metadata",
          "std::fs::write",
          "std::fs::create_dir",
          "std::fs::read_dir",
          "std::fs::ReadDir",
          "std::fs::DirEntry",
          "std::fs::remove_dir_all",
          "std::fs::FileType",
          "std::fs::copy",
          "std::fs::rename",
          "std::fs::remove_dir",
          "std::fs::soft_link",
          "std::fs::File",
          "std::thread::ThreadId",
          "std::thread",
          "std::thread::park",
          "std::thread::AccessError",
          "std::thread::panicking",
          "std::thread::park_timeout_ms",
          "std::thread::park_timeout",
          "std::thread::spawn",
          "std::thread::JoinHandle",
          "std::thread::local::AccessError",
          "std::thread::local::LocalKey",
          "std::thread::current",
          "std::thread::sleep_ms",
          "std::thread::Thread",
          "std::thread::Builder",
          "std::thread::LocalKey",
          "std::thread::sleep",
          "std::thread::Result",
          "std::thread::yield_now",
          "std::thread::available_concurrency",
          "std::rc",
          "std::rc::Weak",
          "std::rc::Rc",
          "std::error::Chain",
          "std::error",
          "std::error::Error",
          "std::if",
          "std::debug_assert_ne!",
          "std::match",
          "std::future",
          "std::future::poll_fn",
          "std::future::Ready",
          "std::future::ready",
          "std::future::Future",
          "std::future::PollFn",
          "std::future::Pending",
          "std::future::pending",
          "std::future::IntoFuture",
          "std::todo!",
          "std::u16",
          "std::u16::MAX",
          "std::u16::MIN",
          "std::panic!",
          "std::prim_usize",
          "std::i16",
          "std::str::SplitAsciiWhitespace",
          "std::str::CharIndices",
          "std::str::EscapeDebug",
          "std::str::SplitN",
          "std::str",
          "std::str::from_utf8_unchecked",
          "std::str::from_utf8_unchecked_mut",
          "std::str::Bytes",
          "std::str::SplitTerminator",
          "std::str::Lines",
          "std::str::EncodeUtf16",
          "std::str::SplitWhitespace",
          "std::str::Split",
          "std::str::EscapeUnicode",
          "std::str::RMatchIndices",
          "std::str::LinesAny",
          "std::str::from_boxed_utf8_unchecked",
          "std::str::Utf8Error",
          "std::str::SplitInclusive",
          "std::str::FromStr",
          "std::str::MatchIndices",
          "std::str::from_utf8_mut",
          "std::str::Chars",
          "std::str::RSplitN",
          "std::str::Matches",
          "std::str::ParseBoolError",
          "std::str::from_utf8",
          "std::str::pattern::SearchStep",
          "std::str::pattern::StrSearcher",
          "std::str::pattern::Searcher",
          "std::str::pattern",
          "std::str::pattern::CharSliceSearcher",
          "std::str::pattern::Pattern",
          "std::str::pattern::CharPredicateSearcher",
          "std::str::pattern::ReverseSearcher",
          "std::str::pattern::DoubleEndedSearcher",
          "std::str::pattern::CharSearcher",
          "std::str::RSplitTerminator",
          "std::str::RMatches",
          "std::str::RSplit",
          "std::str::EscapeDefault",
          "std::loop",
          "std::trait",
          "std::eprint!",
          "std::prim_f32",
          "std::prim_pointer",
          "std::return",
          "std::fn",
          "std::prim_u8",
          "std::module_path!",
          "std::prim_slice",
          "std::usize",
          "std::mem::align_of_val_raw",
          "std::mem::size_of_val",
          "std::mem::align_of_val",
          "std::mem",
          "std::mem::uninitialized",
          "std::mem::transmute",
          "std::mem::take",
          "std::mem::drop",
          "std::mem::needs_drop",
          "std::mem::Discriminant",
          "std::mem::swap",
          "std::mem::variant_count",
          "std::mem::size_of",
          "std::mem::transmute_copy",
          "std::mem::size_of_val_raw",
          "std::mem::min_align_of",
          "std::mem::discriminant",
          "std::mem::ManuallyDrop",
          "std::mem::forget",
          "std::mem::forget_unsized",
          "std::mem::replace",
          "std::mem::align_of",
          "std::mem::zeroed",
          "std::mem::MaybeUninit",
          "std::mem::min_align_of_val",
          "std::convert::TryFrom",
          "std::convert::TryInto",
          "std::convert",
          "std::convert::identity",
          "std::convert::Infallible",
          "std::convert::Into",
          "std::convert::AsRef",
          "std::convert::FloatToInt",
          "std::convert::From",
          "std::convert::AsMut",
          "std::static",
          "std::f64",
          "std::char",
          "std::process::abort",
          "std::process::ExitCode",
          "std::process::ChildStdout",
          "std::process",
          "std::process::ExitStatus",
          "std::process::Stdio",
          "std::process::Child",
          "std::process::ChildStderr",
          "std::process::ExitStatusError",
          "std::process::Termination",
          "std::process::Command",
          "std::process::CommandArgs",
          "std::process::id",
          "std::process::Output",
          "std::process::ChildStdin",
          "std::process::CommandEnvs",
          "std::process::exit",
          "std::is_aarch64_feature_detected!",
          "std::array",
          "std::panicking::take_hook",
          "std::panicking::set_hook",
          "std::matches!",
          "std::assert_ne",
          "std::prim_never",
          "std::f64::NAN",
          "std::f64::MIN_10_EXP",
          "std::f64",
          "std::f64::MAX",
          "std::f64::MIN",
          "std::f64::EPSILON",
          "std::f64::MAX_10_EXP",
          "std::f64::MIN_EXP",
          "std::f64::RADIX",
          "std::f64::MIN_POSITIVE",
          "std::f64::MAX_EXP",
          "std::f64::MANTISSA_DIGITS",
          "std::f64::INFINITY",
          "std::f64::consts::FRAC_PI_6",
          "std::f64::consts::E",
          "std::f64::consts",
          "std::f64::consts::LOG2_10",
          "std::f64::consts::PI",
          "std::f64::consts::FRAC_PI_2",
          "std::f64::consts::LOG10_2",
          "std::f64::consts::FRAC_PI_3",
          "std::f64::consts::SQRT_2",
          "std::f64::consts::LOG10_E",
          "std::f64::consts::FRAC_1_PI",
          "std::f64::consts::FRAC_2_SQRT_PI",
          "std::f64::consts::FRAC_PI_4",
          "std::f64::consts::LN_10",
          "std::f64::consts::FRAC_1_SQRT_2",
          "std::f64::consts::FRAC_PI_8",
          "std::f64::consts::TAU",
          "std::f64::consts::FRAC_2_PI",
          "std::f64::consts::LN_2",
          "std::f64::consts::LOG2_E",
          "std::f64::DIGITS",
          "std::f64::NEG_INFINITY",
          "std::use",
        ],
      },
    },
    {
      name: "man",
      description: "View the man page for a given command",
      options: [
        {
          name: ["-h", "--help"],
          description: "Prints help information",
        },
        {
          name: "--toolchain",
          description:
            "Toolchain name, such as 'stable', 'nightly', or '1.8.0'",
          args: {
            name: "<toolchain>",
            description:
              "Toolchain name, such as 'stable', 'nightly', or '1.8.0'",
          },
        },
      ],
    },
    {
      name: "self",
      description: "Modify the rustup installation",
      options: [
        {
          name: ["-h", "--help"],
          description: "Prints help information",
        },
      ],
      subcommands: [
        {
          name: "update",
          description: "Download and install updates to rustup",
          options: [
            {
              name: ["-h", "--help"],
              description: "Prints help information",
            },
            {
              name: ["-V", "--version"],
              description: "Prints version information",
            },
          ],
        },
        {
          name: "uninstall",
          description: "Uninstall rustup",
          options: [
            {
              name: ["-h", "--help"],
              description: "Prints help information",
            },
            {
              name: ["-V", "--version"],
              description: "Prints version information",
            },
          ],
        },
        {
          name: "updrade-data",
          description: "Upgrade the internal data format",
          options: [
            {
              name: ["-h", "--help"],
              description: "Prints help information",
            },
            {
              name: ["-V", "--version"],
              description: "Prints version information",
            },
          ],
        },
        {
          name: "help",
          description:
            "Prints this message or the help of the given subcommand(s)",
          args: {
            name: "subcommand(s)",
            isOptional: true,
          },
        },
      ],
    },
    {
      name: "set",
      description: "Alter rustup settings",
      options: [
        {
          name: ["-h", "--help"],
          description: "Prints help information",
        },
      ],
      subcommands: [
        {
          name: "auto-self-update",
          description: "The rustup auto self update mode",
          args: {
            name: "<auto-self-update-mode>",
            default: "enable",
            isOptional: true,
            suggestions: ["enable", "disable", "check-only"],
          },
          options: [
            {
              name: ["-h", "--help"],
              description: "Prints help information",
            },
            {
              name: ["-V", "--version"],
              description: "Prints version information",
            },
          ],
        },
        {
          name: "default-host",
          options: [
            {
              name: ["-h", "--help"],
              description: "Prints help information",
            },
            {
              name: ["-V", "--version"],
              description: "Prints version information",
            },
          ],
          args: {
            name: "<host_triple>",
          },
        },
      ],
    },
    {
      name: "completions",
      description: "Generate tab-completion scripts for your shell",
      options: [
        {
          name: ["-h", "--help"],
          description: "Prints help information",
        },
      ],
      args: [
        {
          name: "<shell>",
          suggestions: ["zsh", "bash", "fish", "powershell", "elvish"],
        },
        {
          name: "<command>",
          suggestions: ["rustup", "cargo"],
        },
      ],
    },
    {
      name: "help",
      description: "Prints this message or the help of the given subcommand(s)",
      args: {
        name: "<subcommand>",
        isVariadic: true,
        isOptional: true,
      },
    },
  ],
  options: [
    {
      name: ["-h", "--help"],
      description: "Prints help information",
    },
    {
      name: ["-V", "--version"],
      description: "Prints version information",
    },
    {
      name: ["-q", "--quiet"],
      description: "Disable progress output",
    },
    {
      name: ["-v", "--verbose"],
      description: "Enable verbose output",
    },
  ],
  args: {
    name: "toolchain",
    description:
      "Release channel (e.g. +stable) or custom toolchain to set override",
    isOptional: true,
  },
};

export default completionSpec;
