const completionSpec: Fig.Spec = {
  name: "sake",
  description:
    "🍶 Swift-based utility for managing command execution with dependencies and conditions, inspired by Make",
  subcommands: [
    {
      name: "init",
      description:
        "Initialize a new SakeApp project template for defining commands",
    },
    {
      name: "clean",
      description:
        "Remove all build artifacts generated by the SakeApp to ensure a clean state for future builds",
    },
    {
      name: "list",
      description: "List all available commands defined in the SakeApp",
      options: [
        {
          name: "--case-converting-strategy",
          description:
            "Specify the strategy for converting command names' case",
          args: {
            name: "strategy",
            default: "keepOriginal",
            suggestions: ["keepOriginal", "toSnakeCase", "toKebabCase"],
          },
        },
        {
          name: ["--json", "-j"],
          description: "Output the list of commands in JSON format",
        },
      ],
    },
    {
      name: "run",
      description: "Run the specified command from the SakeApp",
      args: {
        name: "command",
        description: "The command to run",
        generators: {
          script: ["sake", "list", "--json"],
          postProcess: function (output) {
            const commands = JSON.parse(output);
            return Object.keys(commands.groups).reduce((acc, groupName) => {
              const group = commands.groups[groupName];
              return [
                ...acc,
                ...group,
              ];
            }, [])
          }
        }
      },
      options: [
        {
          name: "--case-converting-strategy",
          description:
            "Specify the strategy for converting command names' case",
          args: {
            name: "strategy",
            default: "keepOriginal",
            suggestions: ["keepOriginal", "toSnakeCase", "toKebabCase"],
          },
        },
      ],
    },
  ],
  options: [
    {
      name: ["--help", "-h"],
      description: "Show help information",
      isPersistent: true,
    },
    {
      name: ["--config-path", "-c"],
      description: "Specify the path to the configuration file",
      isPersistent: true,
    },
    {
      name: ["--sake-app-path", "-s"],
      description: "Specify the path for the SakeApp package",
      isPersistent: true,
    },
  ],
};
export default completionSpec;
